### ISSUE TITLE
Intermittent: login attempt to https://registry.hub.docker.com/v2/ failed with status: 401 Unauthorized

### ISSUE THREAD

**Issue by mkj28** [docker/hub-feedback#1694] opened 2018-11-25 07:56 UTC
## Problem description
Getting this intermittently today (Saturday November 24th):
`login attempt to https://registry.hub.docker.com/v2/ failed with status: 401 Unauthorized`

for example:
around 16:15:47 PST (4:15PM PST)
around 23:05:45 PST (11:05PM PST)

before/between/after these times - same login works perfectly fine

**Comment by manishtomar** [comment] 2018-11-26 07:36
Duplicate of #1693.

**Closed by manishtomar** 2018-11-26 07:36 UTC
