### ISSUE TITLE
Bugfix - Trigger Wildcard Matches for Tags in Automated Builds

### ISSUE THREAD

**Issue by shadowbq** [docker/hub-feedback#384] opened 2015-10-06 01:55 UTC
For automated builds, we should be able to create a REGEX pattern and define, that if a GITHUB / BITBUCKET tag matches the REGEX in the BUILD Settings, it should BUILD and create a docker tag that matches the REGEX pattern

Search: `/v([0-9]+\.[0-9]+\.[0-9]+)/`   Create: `docker-$1`

So if I TAG v1.4.5 in github, I would get in hub.docker `docker-1.4.5` as a build.

http://picpaste.com/pics/Screenshot_-_10052015_-_11_07_10_AM-m54DjgQf.1444096208.png

Using the GITHUB API to check for Tags..

https://developer.github.com/v3/repos/#list-tags

Using the BITBUCKET API to check for Tags.. 

https://bitbucket.org/api/1.0/repositories/{accountname}/{repo_slug}/tags/

**Comment by trinitronx** [comment] 2015-10-21 19:22
:+1:

**Comment by shinyalt** [comment] 2015-12-01 04:22
+2

**Comment by shinymayhem** [comment] 2015-12-01 04:23
+2

**Comment by shadowbq** [comment] 2015-12-01 16:08
This works now.. ! Exactly as stated. go check it out.

**Comment by bcwalrus** [comment] 2015-12-01 23:15
FYI, the back reference syntax is `{\1}`, `{\2}`, etc. In the original example, you want to say `docker-{\1}`.

Note that we're still working on error reporting on invalid tag expression.

**Comment by shadowbq** [comment] 2015-12-02 14:27
Thanks @bcwalrus 
As per the docs for reference..  https://docs.docker.com/docker-hub/builds/
![docker regex-help](https://docs.docker.com/docker-hub/images/regex-help.png)

**Comment by aholbreich** [comment] 2015-12-16 11:43
The default (empty tag) are not working. Also Regex tags are not working in my case...

**Comment by SkypLabs** [comment] 2015-12-31 15:22
Same problem for me ...

**Comment by jrd** [comment] 2016-01-09 12:15
Same here, if docker tag is leave empty and if I try to put `{sourceref}` the field is transformed to blank

**Comment by cur3n4** [comment] 2016-01-14 11:44
Same

**Comment by tanob** [comment] 2016-01-21 02:11
Same here, if I select "Tag", and leave "Name" and "Docker Tag Name" fields empty (to use whatever is in git), when I hit save it saves correctly (I can see the request is correct) but the UI changes back to "Branch" and for some reason Hub is not triggering builds for the git tags.

**Comment by jrd** [comment] 2016-01-21 13:38
How to reopen this? Right now it's marked as « closed »

**Comment by shadowbq** [comment] 2016-01-26 20:23
@bcwalrus - Can you look at **"The default (empty tag) are not working"**

**Comment by jasonmp85** [comment] 2016-03-14 19:54
Is someone looking at this?

Why is this marked as a feature request… it is apparently a regression. #501 implies this was working around three months ago, but no longer does.

I'd like a push of e.g. `v5.0.1` to build Docker tags `5.0.1`, `5.0`, and `5`, but—even though #501 says this can work—tags are not triggering _any_ builds.

What's the status?

**Comment by bcwalrus** [comment] 2016-03-16 17:54
@jasonmp85 Try toggling between "branch" and "tag", save, and change it back. We fixed a UI bug about a month back.

You should be able to specify `/^v([0-9.]+)/` as the pattern in the "Name" field, and `{\1}` (capture group 1) as the Docker tag name. That's the build setting that's I'm using for my builds.

Separately, Hub have issues with older-style Bitbucket service hooks. If your repo is on Bitbucket, try switching to webhooks (url: https://registry.hub.docker.com/hooks/bitbucket) in your Bitbucket repository's settings page.

If that's still not working, could you add a rule for "any tag", and see if that triggers anything?

**Comment by jasonmp85** [comment] 2016-03-16 18:28
:expressionless:

I had my regex set to `/$v(\d+)/`… Carry on.

**Comment by jasonmp85** [comment] 2016-03-16 18:37
In case anyone wants to copy-paste this…

This…

![screen shot 2016-03-16 at 12 32 11 pm](https://cloud.githubusercontent.com/assets/50673/13824327/2806eb72-eb73-11e5-9149-bc75c7f8097f.png)

Results in this (after pushing a tag named `v0.9.1`)…

![screen shot 2016-03-16 at 12 32 00 pm](https://cloud.githubusercontent.com/assets/50673/13824340/38bbb902-eb73-11e5-97d8-08c736ad7273.png)

**Comment by bcwalrus** [comment] 2016-03-16 21:18
@jasonmp85 Thanks for the update! 

Just a suggestion:- If you just want to strip the `v` out of a `vX.Y.Z` version number, you can probably just have 1 rule `/^v([0-9.]+)/`. That will match `v1`, `v1.2`, and `v1.2.3`, etc.

Unfortunately, it'll also match `v1....2` and `v....12`. But if you don't create crazy tags in Git, you should be ok. One single rule is easier to grok.

**Comment by jasonmp85** [comment] 2016-03-16 22:14
@bcwalrus, actually I _don't_ have e.g. `v0.9` in GitHub. Every version is `x.y.z`, but I want Docker to have `x`, `x.y`, and `x.y.z` tags built from a single tag. This seems common in the Docker community (weird as it may seem to me), but it would allow someone to track `project:5` and get 5.0.0, 5.0.1, 5.1.0 as they are released. Or they can be specific and write `project:5.0.0` and it will never change after that single build.

Sorry to be chatty in this issue, just felt like clarifying that workflow since it seems like a common pattern in Docker.

**Comment by bcwalrus** [comment] 2016-03-16 22:32
@jasonmp85 Got it. We're also adding multiple tags per build, which would help a lot.

**Comment by pchico83** [comment] 2016-03-17 06:44
@jasonmp85 A workaround for multitags is to use a "post_push" hook (see details here https://hub.docker.com/r/dockercloud/builder/). `$IMAGE_NAME` has the name of the image to push, you could modify it and push more tags at your convenience.

**Comment by MichaelSimons** [comment] 2016-04-21 18:24
@pchico83 regarding your suggestion on using the "post_push" hook to push the image with a different tag.  What is the recommended way to get authenticated within the post_push script in order to do the push?  I was hoping this script would be able to utilize the authentication scope of the calling build script but that doesn't appear to be the case.  Whenever I make a push request I get `unauthorized: authentication required`.

**Comment by pchico83** [comment] 2016-04-22 11:25
@MichaelSimons Yes, it should use the same auth scope. Are you pushing the tag to the same repository? If not, does the owner of this repo have access to the repository you are pushing to?

**Comment by MichaelSimons** [comment] 2016-04-22 15:49
@pchico83 Yes I am pushing to the same repository.  Here is the post_push script I have been experimenting with.

```
#!/bin/bash

set -e

tagStartIndex=$(expr index "$IMAGE_NAME" :)
baseImageName=$(expr substr $IMAGE_NAME 1 $tagStartIndex)
latestImageName=$baseImageName"latest"

echo "tagging $previewImageName"
docker tag $IMAGE_NAME $latestImageName

echo "pushing $latestImageName"
docker push $latestImageName
```

This results in the following output from the docker hub build.
```
Executing post_push hook...
tagging 
WARNING: Error loading config file:/root/.dockercfg - Invalid auth configuration file
pushing index.docker.io/msimons/dotnet-docker-preview:latest
WARNING: Error loading config file:/root/.dockercfg - Invalid auth configuration file
The push refers to a repository [docker.io/msimons/dotnet-docker-preview]
e82b0195b3fa: Preparing
13b735d1640c: Preparing
591569fa6c34: Preparing
998608e2fcd4: Preparing
5f70bf18a086: Preparing
c12ecfd4861d: Preparing
c12ecfd4861d: Waiting
998608e2fcd4: Layer already exists
998608e2fcd4: Layer already exists
591569fa6c34: Layer already exists
591569fa6c34: Layer already exists
13b735d1640c: Layer already exists
13b735d1640c: Layer already exists
5f70bf18a086: Layer already exists
5f70bf18a086: Layer already exists
e82b0195b3fa: Layer already exists
e82b0195b3fa: Layer already exists
c12ecfd4861d: Layer already exists
c12ecfd4861d: Layer already exists
unauthorized: authentication required
post_push hook failed! (1)
```

**Comment by pchico83** [comment] 2016-04-23 20:39
It fails to load the docker conf file, the file that contains the docker credentials. Can you check the content of this file and see if there is something wrong?

**Comment by pchico83** [comment] 2016-04-25 10:53
@MichaelSimons also, could you try to autobuild from Docker Cloud?

**Comment by MichaelSimons** [comment] 2016-04-25 20:22
@pchico83 I create an autobuild in Docker Cloud for the same Dockerfile and post_push script and everything worked.  I inspected the $DOCKERCFG variables between Docker Hub and Docker Cloud.  The Docker Hub variable looks like the following
```
{"auths": {"https://index.docker.io/v1/": {"email": "xxx@docker.com", "auth": "xxxxxxxxxxxxxxx"}}}
```
The Docker Cloud variable has two auth entries but doesn't contain the outer auths element.
```
{"https://registry-1.docker.io/v1/": {"email": "xxxmyemailxxx", "auth": "yyyyyyyyyyyyyy", "serveraddress": "registry-1.docker.io"}, "https://index.docker.io/v1/": {"email": "xxxmyemailxxx", "auth": "XXXXXXXXXXXX", "serveraddress": "registry-1.docker.io"}}
```
I updated my post_push script to update the /root/.dockercfg to just contain the contents of the auths element and then everything works.

Is it correct to assume this should work "out of the box" in Docker Hub?  Should an issue be logged for this?

**Comment by pchico83** [comment] 2016-04-26 08:58
@MichaelSimons Yes, I opened an issue to fix it in Hub. I will get back to this issue when it is fixed, but you can make use of Docker Cloud Build service in the meantime. We recommend to switch to Docker Cloud Build service since it is more actively maintain and it has some more features as executing tests for pull requests, the ability to define build env variables or the ability to execute the builds in your own nodes to improve performance.

**Comment by leifg** [comment] 2016-07-28 15:50
It seems like the user interface prohibits me from doing that:

Whenever I try to use the regexp capture groups I'll get the error:

`{\1}: Invalid 'name' field: Unknown variable '\1' at position 2Error Saving`

**Comment by bcwalrus** [comment] 2016-07-28 21:42
@leifg What is the regex you use? And it this in Hub or Cloud?

**Comment by leifg** [comment] 2016-07-28 21:47
This is hub. The regey is {\1}

**Comment by bcwalrus** [comment] 2016-07-28 22:32
@leifg The regex should be a regex you use to match a GitHub (or Bitbucket) branch/tag name. That's the "Name" field. That regex should contain a capture group. Then, you can use `{\1}` in the Docker Tag Name to construct the tag name that you want.

Jason provided an example above: https://github.com/docker/hub-feedback/issues/384#issuecomment-197478364

**Comment by leifg** [comment] 2016-07-28 22:48
Sorry, was confused. The regex I used was `erlang-([0-9\.]+)`. The `{\1}` was in the name field.

It does however not work, I actually used Jason's example. Doesn't matter which regex I use (even `(.*)`) there is no way I can save the configuration.

See Screenshot:

![screenshot 2016-07-29 00 42 53](https://cloud.githubusercontent.com/assets/110321/17232094/13b16c8e-5526-11e6-8c9a-9c80eb0c1fb9.png)

**Comment by bcwalrus** [comment] 2016-07-29 16:22
Could you try `\erlang-([0-9\.]+)\`? Without the surrounding backslashes `\`, the name is interpreted as a literal match.

**Comment by leifg** [comment] 2016-07-29 16:33
Changing the regex to `/erlang-([0-9\.]+)/` works.

The error message is confusing though. I assumed the whole time there is something wrong with the Docker Tag Name.

**Comment by bcwalrus** [comment] 2016-08-01 22:57
@leifg You're right. And thanks for the feedback. I'll see what I can do.

**Closed by bcwalrus** 2016-08-01 22:57 UTC
Labels: feature-request

**Comment by ntquyen** [comment] 2016-12-23 10:07
Wonder why the `{\1}` stuff is not in the documentation. For a long time, I have been assuming that only `{sourceref}` supported. One more line of example on `{\1}` in the documentation could have helped a lot.

**Comment by sanscontext** [comment] 2016-12-27 22:11
@ntquyen This was added to the Cloud docs: https://docs.docker.com/docker-cloud/builds/automated-build/#/regexes-and-automated-builds

**Comment by 1138-4EB** [comment] 2017-03-02 19:15
Hello, I am trying to use `^img-(.+)` to match some branches, but it won't work. The tag name is `{\1}`, and these are the branches I want to catch:

| Branch name | Desired tag name |
|---|---|
| img-fedora-llvm-mcode | fedora-llvm-mcode |
| img-ubuntu-mcode | ubuntu-mcode |
| img-ubuntu1204-llvm | ubuntu1204-llvm |
| img-ubuntu1404-llvm | ubuntu1404-llvm |

These are the errors I get:

- With `/^img-(.+)/`, no match is found, so the 'Trigger' button is not shown.
- With  `^img-(.+)`, `\^img-(.+)\` or `{^img-(.+)}`, the 'Trigger' button is shown, but the following error is given when saving: *Invalid 'name' field: Unknown variable '\1' at position 2*

As I referred in #959, the regular expression is correct according to regex101.com and regexpal.com.

Compared to @leifg's comment [above](https://github.com/docker/hub-feedback/issues/384#issuecomment-236228828), th only difference is that he uses `([0-9\.]+)` instead of `(.+)`.
