### ISSUE TITLE
specify Dockerfile name not only location

### ISSUE THREAD

**Issue by dciccale** [docker/hub-feedback#371] opened 2015-09-30 09:56 UTC
would be really useful to be able to specify the file (not only the location) from where to build the image.

now you can only specify the directory on where the Dockerfile is located. 

however using docker cli you can pass `-f whatever`

in my repo i have `Dockerfile` `Dockerfile-staging` and `Dockerfile-dev` and without this feature i am forced to create a `Dockerfile-staging` directory and throw in a `Dockefile` and the same for `Dockerfile-dev`  which i find kind of annoying

thx

**Comment by modius** [comment] 2015-10-02 07:09
> It's been months since the release of this functionality in Docker itself. Is there any ETA on when this might be available in Docker Hub?
> https://forums.docker.com/t/automated-build-on-docker-hub-is-there-a-way-to-specify-a-dockerfile/1078

+1

**Comment by DBarney** [comment] 2015-10-13 19:34
I have multiple Dockerfiles in one repo for different versions of a program. Being able to choose one of them would extremely useful, as right now I can do it with the cli, but can't use the automated build because of this missing feature.

+1

**Comment by nhuray** [comment] 2015-10-14 18:08
+1

**Comment by MathieuLescure** [comment] 2015-10-14 18:10
+1

**Comment by rodablo** [comment] 2015-10-23 20:36
I have multiple generated Dockerfiles for different variants of the same product.

**Comment by ChristopherBiscardi** [comment] 2015-11-06 21:23
closing as dupe of https://github.com/docker/hub-feedback/issues/292

**Closed by ChristopherBiscardi** 2015-11-06 21:23 UTC

**Comment by markoshust** [comment] 2016-11-11 21:47
#292 is open, last comment says info soon. but it's from february, and thread is locked. any update on this?

**Comment by nazar-pc** [comment] 2017-02-11 23:48
@markoshust, I've just moved all `Dockerfile`s to the root of my repository and renamed them into `Dockerfile-data`, `Dockerfile-nginx` and so on. I've also specified them as `/Dockerfile-data` in `Dockerfile Location` on Docker Hub and it works fine for me.
@rrarunan, maybe it is time to close #292?

**Comment by pkennedyr** [comment] 2017-02-13 16:42
Specifying unique Dockerfile names is now supported in Docker Hub - simply input the filename (e.g. /Dockerfile2) in the "Dockerfile location" from a given build rule.

Note: If you haven't yet, I invite you to take a look at Docker Cloud to create and manage your repositories and auto builds, as it includes many additional features not found in Docker Hub such as specifying build context.

**Comment by 1138-4EB** [comment] 2017-03-25 22:23
@markoshust, I am trying to set three different files on the root of my repository, just as you explained. But I get:
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Build path does not exist: ./Dockerfile-ubuntubase
```
This is the repo: https://github.com/1138-4EB/elide
And these the build logs:

- https://hub.docker.com/r/11384eb/elide/builds/bqtkw2wmniqwwqigtctb7db/
- https://hub.docker.com/r/11384eb/elide/builds/b9fggriukw26lychduejewh/
- https://hub.docker.com/r/11384eb/elide/builds/bpk87ajhrgvmzdwoaza876e/

Is any additional step required?
