### ISSUE TITLE
No title on image pages

### ISSUE THREAD

**Issue by sonotude** [docker/hub-feedback#680] opened 2016-05-26 14:44 UTC
https://hub.docker.com/_/rabbitmq/ and other pages have no title metadata.

ie. in the source html `<title></title>`

OS: Windows 10
Browser: Chrome 50.0.2661.102 m
![image](https://cloud.githubusercontent.com/assets/5854391/15578473/7c62de02-2358-11e6-9189-f0c49bef7248.png)

**Comment by ypcs** [comment] 2016-06-07 06:01
This is duplicate of #396 (and #124 #125, already closed but issue remains).

**Comment by doebi** [comment] 2016-06-08 13:17
Honestly, this bug is freaking me out.
While having multiple tabs of hub.docker.com open, i cannot easily spot which is which.

This could be fixed so easily. Why isn't it happening?

**Comment by alexQueue** [comment] 2016-06-30 15:34
It's all pages on docker hub, not just image pages.

And it's driving me crazy.

**Comment by pkennedyr** [comment] 2016-09-28 21:05
Hi All, Page titles are now available on Docker Hub:

![screen shot 2016-09-28 at 2 03 45 pm](https://cloud.githubusercontent.com/assets/16218086/18932267/78a06788-8584-11e6-9979-69d3f792f66d.png)

**Closed by pkennedyr** 2016-09-28 21:05 UTC
Labels: bug
