### ISSUE TITLE
Cancelled builds trigger (indistinguishable) webhooks

### ISSUE THREAD

**Issue by Patricol** [docker/hub-feedback#1784] opened 2019-04-05 21:35 UTC
### Preamble:
Cancelling builds via the docker hub/cloud web GUI seems to do nothing but prevent images being pushed after the build completes. Cancelling dozens of builds at the same time prevents any other builds from starting until the 'shadow builds' finish running the background.

### Issue:
Cancelled builds trigger webhooks upon their 'completion' (which can occur many hours after their cancellation;) and the json payload sent with the POST request is indistinguishable from the payload for a completed build that was not cancelled.

### Proposed Solutions:
- Ideally there could be some way of distinguishing payloads from cancelled builds.
- If cancelled builds triggering webhooks is unintended functionality; perhaps it can be removed.

**Comment by erikmd** [comment] 2019-04-14 11:53
I've noticed a similar issue with the automated build repo https://hub.docker.com/r/coqorg/coq/ :

* the cancelled builds still run until the end, as shown by the build logs that appear after a while;
* **the resulting images of cancelled builds are pushed all the same**;
* and **cancelling a build doesn't "free" the build pipeline** so all other builds are unexpectedly pending;
* the only difference with a non-cancelled build is that cancelled builds don't show up in the [builds list](https://hub.docker.com/r/coqorg/coq/builds)…

Hopefully you can take a look at this issue.

**Comment by erikmd** [comment] 2019-05-29 20:37
Dear Docker Hub maintainers,

This issue #1784 is still reproducible in the automated build repo [`mathcomp/mathcomp`](https://hub.docker.com/r/mathcomp/mathcomp) maintained by @CohenCyril and I, as shown by the screenshot at the bottom of this comment, taken from
https://cloud.docker.com/u/mathcomp/repository/docker/mathcomp/mathcomp/timeline

To sum up, the "Cancel" feature is broken (cf. the four items in my [previous comment](https://github.com/docker/hub-feedback/issues/1784#issuecomment-482957426)) and AFAICT this is a major issue because after waiting for more than 12h in our case, the build pipeline is still "blocked" with no relevant build…

Do you know when this issue could be solved?

Thank you for your time,
Erik

<details><summary>Screenshot</summary>

![2019-05-29_22-22-41_Screenshot_mathcomp_Timeline](https://user-images.githubusercontent.com/10367254/58588649-684f2780-8260-11e9-9d6e-2559efe023e6.png)

</details>

**Comment by erikmd** [comment] 2019-05-29 21:28
Also, maybe someone could rename this issue to make it explicit that it is not only webhooks-related…
e.g. something like this? `Cancelled builds are not properly cancelled, they trigger docker push and webhooks upon (unwanted) completion`

@Patricol do you agree?

**Comment by erikmd** [comment] 2019-06-06 00:44
Dear @meticulous-dft @Patricol, would one of you agree to rename the issue as [suggested](https://github.com/docker/hub-feedback/issues/1784#issuecomment-497099777)?

@meticulous-dft do you know if this issue could be investigated soon?

Best regards

**Comment by meticulous-dft** [comment] 2019-06-07 15:39
Add @sarkis for visibility

**Comment by Patricol** [comment] 2019-06-07 22:50
@erikmd 

The cancelled-builds-not-actually-getting-cancelled issue has been around for so long (and is so eminently observable) that I just assumed it was known and potentially wontfix.

That's why I described it in a preamble section; just introducing it as prerequisite knowledge. Partially because I didn't want to search through every issue from the past few years to find the ones that describe that (cancelled-builds-not-actually-getting-cancelled) behavior.

I meant for this issue to be more laser-targeted on the obviously undesired behavior of triggering indistinguishable webhooks. The other behavior is also obviously undesired; but is less of a user-facing issue than an efficiency issue. ("it takes forever" instead of "it breaks things")

I want both problems fixed as well, but I'd imagine there should be an existing issue for the cancelled-builds-not-actually-getting-cancelled problem, because that has been around forever.

**Comment by sarkis** [comment] 2019-06-07 23:19
> I meant for this issue to be more laser-targeted on the obviously undesired behavior of triggering indistinguishable webhooks. The other behavior is also obviously undesired; but is less of a user-facing issue than an efficiency issue. ("it takes forever" instead of "it breaks things")

I can tell you that internally we are tracking both as high priority and *separate* issues and we should have a fix shortly.

**Comment by sarkis** [comment] 2019-06-14 04:11
@Patricol specific to the issue in this ticket, I have been unsuccessful in reproducing the issue described where cancelled builds will trigger webhooks. 

Would you have more information about your setup in case there is anything specific there that could help me reproduce this on my end?

**Comment by Patricol** [comment] 2019-06-14 04:26
@sarkis 

I believe the builds in question were triggered with a POST request and cancelled with the website UI.

The webhooks triggered a cloud function; not another build directly.

I can give more detail if you are still unable to reproduce.

**Comment by sarkis** [comment] 2019-06-14 04:55
The webhook trigered by the canceled builds are ones set on the docker hub repository? Did you notice the canceled build push an image? I ask because the only way I've been able to trigger a webhook has been by pushing a new image.

**Comment by Patricol** [comment] 2019-06-14 05:14
@sarkis 

> The webhook triggered by the canceled builds are ones set on the docker hub repository?
Yes.

> Did you notice the canceled build push an image?
The image does not appear to be replaced; but Docker Hub's "Updated" time is updated as if it was.

I remember that the webhooks' JSON payloads were truly indistinguishable; so if they normally contain any ID for a built image; then an ID was included. I tried looking through logs for old builds; but old logs seem to have been removed on Docker Hub. If you can still access old logs; I can use the timestamps for the cancelled builds of patricol/cascade-build to find corresponding JSON payloads.

**Comment by erikmd** [comment] 2019-06-14 14:57
@sarkis FYI I have just tested again this issue, and I think I have reproduced the two issues at once:

In the https://hub.docker.com/r/coqorg/coq/ repo, I have performed the following steps:
* First, I took a screenshot of the `coqorg/coq:dev` image metadata https://microbadger.com/images/coqorg/coq:dev (the update being triggered by a Docker Hub webhook)
* I triggered manually the rebuild of `coqorg/coq:dev`, then that of `coqorg/coq:8.10-beta1`
* And I immediately cancelled the build of `coqorg/coq:dev` (which takes 90' to complete in general)
* As (un)expected, the `coqorg/coq:dev` was built anyway and pushed… before `coqorg/coq:8.10-beta` was started
* And I finally I took another screenshot of the `coqorg/coq:dev` image metadata https://microbadger.com/images/coqorg/coq:dev (which should not have been changed in a regular situation)

### Screenshot of `coqorg/coq:dev` before the test

![2019-06-14_11-29-40_Screenshot_coqorg_coq_microbadger_before](https://user-images.githubusercontent.com/10367254/59517938-fb28cc80-8ec4-11e9-9ee0-5ccf57e8b625.png)

### Screenshots after the two builds (the not-really-cancelled one and and the regular one)

![2019-06-14_16-43-18_Screenshot_coqorg_coq_Timeline](https://user-images.githubusercontent.com/10367254/59517970-067bf800-8ec5-11e9-899c-39e51a48b848.png)

![2019-06-14_16-52-20_Screenshot_coqorg_coq_microbadger_now](https://user-images.githubusercontent.com/10367254/59518005-172c6e00-8ec5-11e9-9ee3-70a3303a52ef.png)

![2019-06-14_16-49-40_Screenshot_coqorg_coq_tags](https://user-images.githubusercontent.com/10367254/59518027-1e537c00-8ec5-11e9-8ab0-986d1210eae9.png)

**Comment by sarkis** [comment] 2019-06-17 15:52
@erikmd thanks for the details, that helped me reproduce the issue on my end this AM. Should have more updates shortly.

**Comment by sarkis** [comment] 2019-06-18 18:54
@erikmd @Patricol I've merged in the fix that should resolve both of your issues. I've tested to the best of my ability trying to reproduce your setups and it passed the test on my end. Please let us know here by reopening the issue if you continue to experience issues.

**Closed** 2019-06-18 19:07 UTC

**Comment by erikmd** [comment] 2019-06-18 19:28
@sarkis Great, thanks a lot!
