### ISSUE TITLE
Can't delete repository

### ISSUE THREAD

**Issue by michaelpetri** [docker/hub-feedback#819] opened 2016-10-08 01:53 UTC
Every time i try to delete a repository i receive the following error: 
> There was an error. The repository was not deleted.

Would be nice if you could fix this or allow users to add automatic builds to existing repositories.

Thanks 

--- 

Operating system: osx 10.11.6
Browser: Chrome Version 53.0.2785.116 (64-bit)
Hub user: michaelpetri
<img width="846" alt="screen shot 2016-10-08 at 03 56 00" src="https://cloud.githubusercontent.com/assets/4114292/19209466/2a0aa514-8d0b-11e6-9af6-9c7bd60147b8.png">

**Comment by bddenhartog** [comment] 2016-10-09 05:48
I'm experiencing the same issue.

**Comment by pkennedyr** [comment] 2016-10-10 00:23
Thanks for the feedback. We are able to reproduce the error and are working on a fix.

**Comment by pkennedyr** [comment] 2016-10-10 04:07
@michaelpetri @bddenhartog A fix for this issue has now been deployed and repositories can now be deleted. Thanks again for the feedback.

**Closed by pkennedyr** 2016-10-10 04:07 UTC
Labels: bug

**Comment by bddenhartog** [comment] 2016-10-10 05:01
Thanks for the quick fix!

**Comment by WesleyBatista** [comment] 2016-10-26 13:28
Still with the problem here :/
![captura de tela 2016-10-26 as 11 27 56](https://cloud.githubusercontent.com/assets/755254/19727705/4c1041d8-9b6f-11e6-91aa-437f36387b73.png)

**Comment by mikehancock** [comment] 2016-10-27 17:34
I am also seeing the same issue

**Comment by pkennedyr** [comment] 2016-10-27 17:47
@WesleyBatista @mikehancock Please open a ticket with support and they will be able to investigate your issue: https://hub.docker.com/help/

**Comment by chriscapetown** [comment] 2016-11-14 16:00
Im also having this problem.

**Comment by hloydl** [comment] 2016-12-08 09:22
Same problem here:
![image](https://cloud.githubusercontent.com/assets/7716757/21004353/2a77e034-bd30-11e6-9e5a-52f82ca2180a.png)

**Comment by rokka-n** [comment] 2016-12-09 20:26
I can't 🚮 repository as well, ay ay ay...

**Comment by dax0** [comment] 2017-01-15 17:33
Same problem here.  If it helps it seems to happen when we push a repo that goes over our limit

**Comment by CloudNetwork** [comment] 2020-07-13 10:42
How can i delete private or public repository from docker hub 

i try with this command 
 curl -s -v -H "Authorization: JWT ${HUB_TOKEN}"  -X DELETE  "https://hub.docker.com/v2/repositories/mohd/test2/" 

got error
400 BAD REQUEST
Connection #0 to host hub.docker.com left intact
{"detail": "There was an error. The repository was not deleted."}


from UI also its not removing and i email to support@docker.com 4 times but no reply came.

@pkennedyr @WesleyBatista @mikehancock

**Comment by wallacepf** [comment] 2021-08-30 22:12
2021....cannot delete a repository.  I'm not getting any error message.

**Comment by Binsabbar** [comment] 2022-01-25 13:56
This issue is open for years and last response is almost 6 months ago. I am a paid customer and not sure where to raise a ticket for support.

The issue is annoying since I have automated my whole process of creating repo in my org. So now I can't pull/push to the repo and I can't delete it.

My only way is to rename my project and push it as new repo :) not really good, but do I have other options?

**Comment by MohdRashid01** [comment] 2022-01-25 14:34
@Binsabbar You can delete a repo, you can renew the repo anything u can do it  whether its a private or public repo. 
see below screenshot 
![image](https://user-images.githubusercontent.com/7812871/150996631-81370085-28b7-4f07-a922-aec88cb81717.png)

**Comment by ratanservegar** [comment] 2022-02-20 13:01
Hi,
This doesn't work even for me. When I delete a repo by providing the name it doesn't delete it 

"There was an error. The repository was not deleted."

**Comment by ingshtrom** [comment] 2022-02-23 15:32
Have you all created support tickets via hub.docker.com? You can get [there](https://hub.docker.com/support/contact/) by going to the nav bar -> help -> support 
![image](https://user-images.githubusercontent.com/571756/155351673-35d5700d-a6c9-4e83-8a5b-bc1db22a573b.png)

**Comment by jumoog** [comment] 2022-05-06 19:23
omg this is a joke!
