### ISSUE TITLE
No way to cancel build

### ISSUE THREAD

**Issue by audreyr** [docker/hub-feedback#395] opened 2015-10-11 18:03 UTC
It would be nice to have a button to click to cancel a build. A [Cancel] button would save a lot of time and unneeded processing.

**Comment by Kaixhin** [comment] 2015-10-16 14:31
FYI, duplicate of https://github.com/docker/hub-feedback/issues/355.

**Comment by rrarunan** [comment] 2016-02-10 17:35
closing as per @Kaixhin. Duplicate.

**Closed by rrarunan** 2016-02-10 17:35 UTC

**Comment by calvinbutcher** [comment] 2016-06-10 13:50
Still no cancel, no update... above thread closed.

**Comment by naartjie** [comment] 2016-06-10 16:55
Yeah, I wonder why it's closed. It would be super useful in some cases, where you do successive pushes to your git repo, and an older build is blocking the latest ones from going through, they just sit in queued for quite a while.

**Comment by Kaixhin** [comment] 2016-06-10 16:57
@calvinbutcher @naartjie this issue has been closed because it is a duplicate of https://github.com/docker/hub-feedback/issues/355, which is still open. The conversation of https://github.com/docker/hub-feedback/issues/355 has been locked to stop +1s as the feature is now triaged.

**Comment by naartjie** [comment] 2016-06-11 08:15
ah our bad than. thanks @Kaixhin

**Comment by calvinbutcher** [comment] 2016-06-13 13:58
OK, the triage has been around for 4 months so thought it had been forgotten.

**Comment by aatkinson-canopy** [comment] 2016-07-27 19:39
Guys, need a 'Cancel' button. Thanks.

**Comment by pchico83** [comment] 2016-07-28 08:16
This is available in Docker Cloud. Docker Cloud is integrated with your Hub repositories, they are accessible from both platforms.

**Comment by iahmad-khan** [comment] 2016-08-19 14:17
please add a cancel button , please

**Comment by pkennedyr** [comment] 2016-08-29 19:12
Support for cancelling builds on Hub is on our roadmap and will be available later this year.

Note: This feature is currently available on Docker Cloud, which is where the majority of improvements and new features will be available: https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498/2https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498/2

**Comment by sacdallago** [comment] 2016-08-31 06:01
@pkennedyr what about hanging builds? Is there a possibility to stop at least those or set a TTL for the build to finish via dockerfile? My auto-build is stuck since hours and spawning new builds won't solve the issue

**Comment by pkennedyr** [comment] 2016-09-29 22:29
We are happy to announce that build cancelation is now available on Docker Hub.

To cancel a build, navigate to the Build Details tab of a repository and click the Cancel button for a given queued or in progress build.

**Comment by d2lam** [comment] 2018-02-16 00:15
This never works for me. Clicking `cancel` does nothing.

**Comment by impredicative** [comment] 2019-03-14 16:35
@pkennedyr  Sorry but a fake cancel button that doesn't work isn't a resolution to the issue. I am pretty serious. There are at least five users who have posted at https://github.com/docker/hub-feedback/issues/1352 in the last 24 hours noting that the Cancel button doesn't work. I am another. And because it doesn't work, new builds don't run. Isn't there even a proper timeout?
