### ISSUE TITLE
entrypoint build issue

### ISSUE THREAD

**Issue by pontostroy** [docker/hub-feedback#821] opened 2016-10-09 06:05 UTC
This work great few days ago on docker hub (on local machine all works fine)
USER gog
COPY ./env.sh /home/gog/.bashrc
COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

but now i get 

Build failed: stat /var/lib/docker/overlay/c5ade468eba62df5fcaebb2b1f5f48dc752e4d198dcde38c78393ce1f7847665/merged/docker-entrypoint.sh: no such file or directory

**Comment by HariSekhon** [comment] 2016-10-10 10:03
I've got this across more than one build that used to work before, eg.

https://hub.docker.com/r/harisekhon/hadoop-dev/builds/bxpwhyiasbq9kjropreer9n/

**Comment by avoinea** [comment] 2016-10-12 18:09
Same here: https://hub.docker.com/r/eeacms/plone-test/builds/b9haxod8tk3qkgrbgrm3xzj/

**Comment by HariSekhon** [comment] 2016-10-12 18:17
This is a really bug as it's broken all my automated builds which are now no longer updating because of this issue.

**Comment by HariSekhon** [comment] 2016-10-12 18:21
I've just raised a ticket with a more serious headline pointing to this one since nobody has responded to this in days and it's blocking many builds.

**Comment by pkennedyr** [comment] 2016-10-12 18:36
Thanks for the feedback. The team is aware of the issue and is actively working on a fix.

**Comment by pkennedyr** [comment] 2016-10-12 19:34
@HariSekhon We have rolled back a deployment which appears to have caused your specific build failures. Can you please retrigger your builds and let us know if you are still experiencing the issue?

Thanks.

**Comment by HariSekhon** [comment] 2016-10-15 08:50
This is still occurring on builds:

https://hub.docker.com/r/harisekhon/zookeeper-dev/builds/bxehtatrmgghafvqxd7znud/

https://hub.docker.com/r/harisekhon/hadoop-dev/builds/bhxbiewdu7j9a9gru2jynst/

https://hub.docker.com/r/harisekhon/hadoop-dev/builds/bnto9gceombvydziarxdqka/

**Comment by AndrewDryga** [comment] 2016-10-15 14:03
Still occurring on build: 
https://hub.docker.com/r/nebo15/alpine-cassandra/builds/bcwdjqnt4dbtisif8t2ckxo/

**Comment by pkennedyr** [comment] 2016-10-15 21:16
@HariSekhon @AndrewDryga. Thanks for confirming. It appears that a small percentage of overall build traffic is still experiencing this issue, so the team is working to address a fix and will be releasing another update early next week.

We apologize for the inconvenience and will continue to posting updates to this thread as further information is available.

**Comment by aholbreich** [comment] 2016-10-17 15:18
It seem somehow to be connected to branches/tags?
See failing
https://hub.docker.com/r/gold/ghost/builds/b2yvertsjkrvc3r3gyahz5g/ (build form tag)
burt working
https://hub.docker.com/r/gold/ghost/builds/beunyqnobwzxj5brurwsqkd/ (build from master)

**Comment by aholbreich** [comment] 2016-10-17 15:20
Does Docker hub build logic check out everything from github project? Had simmilar issue months ago. Where files where not included to the build... Very anoing. :(

**Comment by hwdsl2** [comment] 2016-10-18 20:22
This is related to: docker/docker#25925

**Comment by ryanwalls** [comment] 2016-10-20 18:12
@pkennedyr We are still hitting this issue.  Have tried manually triggering the build 4 times now...

**Comment by pkennedyr** [comment] 2016-10-20 18:52
UPDATE: As of this morning (11:50 am PDT), the absolute root cause of this issue has not yet been identified and ~6% of overall build traffic is still experiencing this issue. We have strong reason to believe that it is related to the following Docker engine issue: https://github.com/docker/docker/issues/25925

We are treating this issue as a top priority across Docker and the team is actively working to address it. We apologize for the inconvenience and will update this thread as soon further information is available.

**Comment by insideo** [comment] 2016-10-20 19:08
FWIW, this seems to only fail for me on docker 1.12.2 build hosts; if the build gets scheduled on a 1.12.0 host it seems to work.

**Comment by NicolasCARPi** [comment] 2016-10-24 15:43
If it can help, the elabftw/elabimg is failing with this exact bug. Before I could manage to build it by retrying the build manually. But now it seems that even  that doesn't work :/

I hope you'll be able to fix this bug in a timely manner :)

Keep up the good work!

Regards,
~Nicolas

**Comment by F21** [comment] 2016-10-25 03:49
I've tried rebuilding many times, but it's been consistently failing for me. See my builds here: https://hub.docker.com/r/boostport/hbase-phoenix-all-in-one/builds/

**Comment by abcfy2** [comment] 2016-10-25 04:12
Same issue here: https://hub.docker.com/r/shifudao/nexus3/builds/

You can see `COPY entrypoint.sh /` failed many times.

**Comment by pkennedyr** [comment] 2016-10-25 19:02
UPDATE: The root cause of this issue has been identified and a temporary fix was deployed to production last night (11pm PDT), which has prevented subsequent occurrences of this issue. The upcoming release of Docker engine 1.12.3 includes an update that we have strong reason to believe will address the root cause of this issue. The team continues to treat this as a top priority and we will be updating this thread as more information is available.

**Comment by aholbreich** [comment] 2016-10-25 21:57
@pkennedyr  good news. 
P.S. It is possible to retriger failed build job without commiting something new to github?

**Comment by F21** [comment] 2016-10-25 22:01
@aholbreich If you manage the repository through cloud.docker.com, you can restart the build.

**Comment by tm-lmathieu** [comment] 2016-10-25 22:04
@aholbreich You can also delete the tag on github then push the same tag again.

**Comment by thasmo** [comment] 2016-10-28 14:46
I'm still experiencing this problem tho.

**Comment by pchico83** [comment] 2016-10-28 20:31
@thasmo could you provide your docker repo? I thought the issue was solved in our latest release

**Comment by thasmo** [comment] 2016-10-28 20:54
@pchico83 Sure! It's https://github.com/dst-academy/docker-dontstarvetogether/tree/v0.6.0

The actual error is:
```
Step 12 : COPY /docker-entrypoint.sh /entrypoint.sh
Removing intermediate container 30d5573f235e
stat /var/lib/docker/overlay/b7805a9da96039a8e0a3a1075fdab81b2d8a3cb8a568096da86822ea3af9483d/merged/entrypoint.sh: no such file or directory
ERROR: Build failed: stat /var/lib/docker/overlay/b7805a9da96039a8e0a3a1075fdab81b2d8a3cb8a568096da86822ea3af9483d/merged/entrypoint.sh: no such file or directory
ERROR: Build failed with exit code 2
ERROR: Build in 'v0.6.0:/build/' (20731160) failed in 0:13:36
```

**Comment by pchico83** [comment] 2016-10-29 05:14
@thasmo I cannot find your failed build. Could you share the build code of the failing build? or the docker repo where this is happening? Note that the fix for this issue was released on last Tuesday (October 25th).

**Comment by thasmo** [comment] 2016-10-29 09:55
@pchico83 I'm building on Docker Cloud. The repo is `dstacademy/dontstarvetogether` and builds sync to the Docker Hub if successful, I believe. I can't figure out any build ID or anything, but I got `BuildTime: 2016-10-11T18:29:41.366230153+00:00` and `Location: Graz, Austria` if that helps you in finding the log or something. Thanks a lot!

**Comment by thasmo** [comment] 2016-10-29 22:16
@pchico83 Seems like it works now, not sure why tho. ;)

**Comment by pkennedyr** [comment] 2016-11-03 18:52
UPDATE: Docker engine 1.12.3 includes an update which addressed the root cause of this build failure. After upgrading the Docker autobuild service to Docker engine 1.12.3, we believe the issue has been resolved as subsequent occurrences of these build failures are no longer occurring. We apologize for the inconvenience and are taking steps to prevent similar issues from occurring in the future.

**Closed by pkennedyr** 2016-11-03 18:52 UTC
