### ISSUE TITLE
Sign Up page shown even when I am logged in

### ISSUE THREAD

**Issue by avinashsonee** [docker/hub-feedback#474] opened 2015-11-18 17:06 UTC
Hi,

I've just created a Docker Hub account and got my email verified.

I'm logged in on hub.docker.com.

Now, I was trying to register on Tutum. I wasn't able to login on Tutum by clicking on 'Login with Docker Hub'. It always throws an error saying "Account not activated" when in fact my Docker hub account is active.

![tutum-login-bug](https://cloud.githubusercontent.com/assets/341604/11247995/c2ce9dbc-8e44-11e5-982f-aa82abd7ed79.png)

Then, on Tutum, I've clicked on 'Create an account with Docker Hub' and it redirects me to this url: https://hub.docker.com/register/?partner_value=tutum 

Since I am already logged in, it should have actually redirected me to Tutum registration page but I am seeing Docker Hub's Sign up page.

Attached below is a screenshot for reference. You can see on the top-right that I am already logged in.

![docker-hub-bug](https://cloud.githubusercontent.com/assets/341604/11247848/e1935338-8e43-11e5-8f3f-deb6ff0cde5c.png)

I've tried testing by directly going to the url: https://hub.docker.com/register/

This also shows me the same sign up page even when I am already logged in.

I think this is a bug and I hope this is the right place to report it.

Thanks,
Avinash Sonee

**Comment by kristiehoward** [comment] 2015-11-18 17:49
hi @avinashsonee, this is the right place to report it :) your hub account is activated (as you are logged in). I was not able to reproduce this bug by following these steps in an incognito browser (to insure I was not logged in to another hub account):
- try to register for tutum
- click `Create an account with Docker Hub`
- sign up for docker hub on https://hub.docker.com/register/?partner_value=tutum
- activate my email address / account by clicking the link in the email
- get redirected to tutum
- set a password on tutum
--> successful registration / login to tutum

Could you let me know if you did something differently so we can try to reproduce it? I'm not sure from your earlier description whether you created a docker hub account with or without the link from tutum (https://hub.docker.com/register/?partner_value=tutum). Additionally, were you logged in to hub already when you clicked on the sign up for docker hub link the first time?

**Comment by rrarunan** [comment] 2015-11-18 18:19
Avinash,

   Can you please try to `Login with Docker hub`, since you already have an account on hub? The `register` is only for new users who don't have an account yet.  The reported issue, is something we are aware of. We are coming up with a solution for users who are already logged in to hub trying to `register` on tutum. In the meantime, let us know if you can `login with Docker hub` successfully. If not, send a note to `support@docker.com` so we can help you further.

Thanks for the report!

**Comment by avinashsonee** [comment] 2015-11-19 05:51
Hi,

As I mentioned clearly that I've created an account on docker hub, verified the email and logged-in.

Then, I tried logging in on tutum. On tutum, I first tried "login with docker hub", which didn't work and thrown an error saying "account not activated" (first screenshot).

Only then, I tried "create an account with docker hub", which took me to the sign up page even when I am logged in to the hub (second screenshot).

I tried the same in incognito mode now. I get the same results as above.

Let me know if you need me to do anything else.

**Comment by avinashsonee** [comment] 2015-11-19 09:43
Hi,

I'm able to login now using Docker Hub. It worked now. Don't know how.

**Comment by maroshii** [comment] 2015-11-19 10:07
Hi @avinashsonee ,
Your Tutum account wasn't active, that's why the linking was failing. We fixed that and reported the issue, it won't happen again. Thanks for your feedback!

**Comment by avinashsonee** [comment] 2015-11-19 10:16
Hi,

Thanks for the update :)

On Thu, Nov 19, 2015 at 3:37 PM, Francisco <notifications@github.com> wrote:

> Hi @avinashsonee <https://github.com/avinashsonee> ,
> Your Tutum account wasn't active, that's why the linking was failing. We
> fixed that and reported the issue, it won't happen again. Thanks for your
> feedback!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/hub-feedback/issues/474#issuecomment-158011217>
> .
>



-- 
Thanks,
Avinash Sonee
9246934603

**Comment by amegianeg** [comment] 2015-11-19 13:53
Fixed in Tutum, can be closed now

**Comment by rrarunan** [comment] 2015-11-19 17:40
Closing.. as per @amegianeg 's update.

**Closed by rrarunan** 2015-11-19 17:40 UTC
Labels: triaged
