### ISSUE TITLE
Docker Hub Auto Build Error Email Links Invalid

### ISSUE THREAD

**Issue by mbentley** [docker/hub-feedback#1980] opened 2020-04-18 11:41 UTC
## Problem description
When you have auto builds and a build fails, you will receive an email like this:
![message](https://user-images.githubusercontent.com/414445/79636745-dede6780-8147-11ea-8a16-db3b0141981d.png)

When you click on the error link, in my case it is https://hub.docker.com/redirect/?resource_uri=/api/audit/v1/action/c72b5469-9006-4a35-b381-242f877b74d8/, it takes me to a 404:
![error](https://user-images.githubusercontent.com/414445/79636750-f1f13780-8147-11ea-9b27-4486ff5378ac.png)

Yes, I am logged in, yes I own the repo and can see logs if I look at the builds.  This has been going on for some time.

**Comment by mattclegg** [comment] 2020-05-10 07:07
The same issue also applies to slack notifications.

**Comment by thaJeztah** [comment] 2020-06-08 09:50
Looks like this is a duplicate of https://github.com/docker/hub-feedback/issues/1957. Let me close this one to prevent the discussion from diverging

**Closed by thaJeztah** 2020-06-08 09:50 UTC

**Comment by mbentley** [comment] 2020-06-08 11:24
It was even me who reported it in the other one 🤦

**Comment by thaJeztah** [comment] 2020-06-08 15:30
Oh! LOL, didn't notice as well 😂
