### ISSUE TITLE
Malicious image ambar/*

### ISSUE THREAD

**Issue by bakrowork** [docker/hub-feedback#1552] opened 2018-06-28 16:45 UTC
https://github.com/RD17/ambar/issues/171

**Comment by jmwong** [comment] 2018-06-29 20:48
Hi @bakrowork thanks for your report. Would you mind elaborating your findings on those images? Has it been actively used in any attacks?

**Comment by nandhini915** [comment] 2018-07-18 21:12
Per https://github.com/RD17/ambar/issues/171 closing this issue since it appears to be a regression in the image. Please comment/open another issue describing the findings if this is actively being used in malicious attacks.

**Closed by nandhini915** 2018-07-18 21:12 UTC
