### ISSUE TITLE
"Save" Button on Builds Edit Page Silently Disregards Entire Form on Error

### ISSUE THREAD

**Issue by GuyPaddock** [docker/hub-feedback#1743] opened 2019-01-26 00:25 UTC
## Problem description 
If I am creating a build configuration OR editing an existing build configuration, and I put in the following auto-build rules:
![image](https://user-images.githubusercontent.com/2631799/51779676-c1eaee00-20d6-11e9-8a30-5d6c64591da9.png)

... and then click "Save", everything I have entered is disregarded silently without an error message. This means:

1. If I was creating a new build configuration, Dockerhub reverts to pretending the project has no linked Git Repositories.
2. If I was editing the build configuration, Dockerhub ignores the attempt to change the configuration and shows me the build configuration and autobuild rules that were in place before my edits.

**Comment by mzachh** [comment] 2019-03-05 18:26
Is there a workaround for this issues? Or are automated builds on Docker Hub really broken since 26th Jan?

**Comment by ljsmith93** [comment] 2019-03-05 18:29
Is there a workaround for this issue? I am also unable to "save" or "save and build".

**Comment by JPZ13** [comment] 2019-03-05 18:56
@GuyPaddock @mzachh @ljsmith93 The cause of this issue is that there are two Docker Tags that are the same with different regexes. @GuyPaddock Can I get you to change the second build rule's Docker Tag from `{\1}` to something else (besides `latest` or `{sourceref}`) and try saving again?

cc @nandhini915

**Comment by ljsmith93** [comment] 2019-03-18 15:44
I tried to delete all build rules and create a single new rule as per the workaround above. However, the system will not save ANY new state. I cannot even delete old builds.

**Comment by nandhini915** [comment] 2019-03-18 16:31
Thanks for confirming @ljsmith93 . We have observed that https://success.docker.com/article/i-have-issues-triggering-autobuilds helped most users get back on track with their autobuilds.

Since you've confirmed you're unable to work on autobuilds, please provide your Docker ID and we can look into it.

**Comment by ljsmith93** [comment] 2019-03-18 17:15
Docker id: ljsmith93

Thank you.

**Comment by nandhini915** [comment] 2019-03-20 16:01
Hi folks, Thanks again for providing this info. We did find an issue in our code, it was a non-obvious issue since most users that had this particular set of problems were due to duplicate tag creation. We have identified and merged the fix, we expect it to get rolled out soon and will let you know once it is rolled out.

**Comment by meticulous-dft** [comment] 2019-03-21 22:58
Hi folks, the fix is deployed to production. Let me know if you still can not change build settings. Thank you.

**Closed by meticulous-dft** 2019-03-21 22:58 UTC
