### ISSUE TITLE
Bad gateway on collaborators page

### ISSUE THREAD

**Issue by blockjon** [docker/hub-feedback#836] opened 2016-10-19 08:17 UTC
I have setup a paid account but when i try to add collaborators I'm getting 502 bad gateway error and so my coworkers cannot access my private repo I created. Please advise!

**Comment by saimonn** [comment] 2016-10-19 08:44
probably duplicate of #833 and #835

**Comment by olegdulin-la** [comment] 2016-10-19 13:48
Yeah we are in the same boat and it does look like a dupe of #833 and #835 ... We are also using a paid account and this is blocking actual work.

**Comment by pkennedyr** [comment] 2016-10-19 15:27
@blockjon @saimonn @olegdulin-la Indeed, this is a dup of #833. The team is currently working on a fix and we'll update #833 as more information is available. Thanks for the feedback.

**Closed by pkennedyr** 2016-10-19 15:27 UTC

**Comment by pkennedyr** [comment] 2016-10-19 20:03
A fix for this issue has now been deployed to prod, which restores access to collaborators settings. We apologize for the inconvenience and please let us know if you experience any further issues.

**Comment by saimonn** [comment] 2016-10-20 08:39
Thanks @pkennedyr !
