### ISSUE TITLE
Download of large layers stalls

### ISSUE THREAD

**Issue by soulshake** [docker/hub-feedback#1225] opened 2017-10-26 10:23 UTC
## The issue

We are currently experiencing major problems pulling large images from Docker Hub to GCE or EC2. The download stalls partway through a given large layer and never finishes.

## What I do

This seems to affect any large image, but here's an example:
`docker pull travisci/ci-amethyst:packer-1508250117-29cd77f`

## What I expect

For the image to download.

## What I see instead

The download stalls partway through:

```
root@instance-2:~/# docker pull travisci/ci-amethyst:packer-1505160600
packer-1505160600: Pulling from travisci/ci-amethyst
48f0413f904d: Pull complete 
[...]
608eabb3bedc: Pull complete 
91fdd994aa8f: Downloading [=======================================>           ]  346.5MB/443.7MB
0c78b2fdb098: Downloading [========>                                          ]  400.1MB/2.439GB
```
It then stays stuck forever.

[This gist](https://gist.github.com/soulshake/445df928904525546fcbeda794d4417c) includes more details.

## Steps to reproduce

Create a plain Ubuntu 14.04 VM on GCE (us-central1-f) or AWS (us-east-1).

Run `docker pull travisci/ci-amethyst:packer-1508250117-29cd77f`.

This is currently reproducible 100% of the time for us, and occurs whether the image layers are retrieved via `docker pull` or `curl` (see reproduction script in gist above).
 
Note: I found that using "-C -" to tell curl to resume an aborted transfer works after aborting and re-running about a dozen times. ([more info](https://gist.github.com/soulshake/445df928904525546fcbeda794d4417c#workaround))

**Comment by nandhini915** [comment] 2017-10-26 10:52
Hi @soulshake - thanks for pointing us to this issue. Could you add details about your docker client via the `docker version` command?

**Comment by nickstenning** [comment] 2017-10-26 11:02
Hi @nandhini915, thanks for getting back to us. I work with @soulshake at Travis CI and this issue appears to be independent of the docker client version. Here's a script that reproduces the action of `docker pull` by making direct requests against the registry:

```shell
#!/bin/sh

set -eu

IMG_NAME=travisci/ci-amethyst
IMG_LAYER=sha256:45464f14df488f191b61d8a409bed2139c88931f060ad70e589bbd10ba4ca3ee

if ! which curl >/dev/null 2>&1; then
  echo "Please ensure that curl is installed (e.g. apt-get install curl)..."
  exit 1
fi

if ! which jq >/dev/null 2>&1; then
  echo "Please ensure that jq is installed (e.g. apt-get install jq)..."
  exit 1
fi

# Get a token
TOKEN=$(curl -sSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${IMG_NAME}:pull" | jq -r .token)

# Fetch the layer
exec curl \
  -SL \
  -H "Authorization: Bearer $TOKEN" \
  -o /dev/null \
  "https://registry-1.docker.io/v2/${IMG_NAME}/blobs/${IMG_LAYER}"
```

At the moment this request for a large layer is stalling across two different infrastructure providers -- which would seem to indicate something is going wrong with the CloudFront distribution serving the registry files.

This also seems to be affecting other customers:

- [CircleCI](https://twitter.com/circleci/status/923412801225310208) is also affected
- [BitBucket](https://twitter.com/BitbucketStatus/status/923434439828430848) is also affected

If possible, can we escalate this issue to the Hub operations team (is it the "distribution services team" we want)? It's been ongoing for >24h and is having significant impact on us and our customers at the moment.

**Comment by nandhini915** [comment] 2017-10-26 11:26
Thanks for adding additional context! We will get back to you as soon as possible.

**Comment by nickstenning** [comment] 2017-10-26 11:42
FWIW it seems like CircleCI have now [officially recognised this issue, too](https://status.circleci.com/incidents/bz6w2805ph3c).

**Comment by tiffanyfj** [comment] 2017-10-26 11:59
@nickstenning Could you check your twitter DMs? Messaged about this issue. Thanks.

**Comment by jpetazzo** [comment] 2017-10-26 12:17
Here is the result of trying to get a layer from all the CloudFront endpoints visible from GCE us-central (obtained with a DNS query). I run `curl` with `-m60` to timeout after 60s. Note how they all downloaded a similar (but not exactly the same) amount of data — as if there was some kind of shaping somewhere but with a super agressive leaky bucket.

```
Trying to get layer on 52.206.156.207...
curl: (28) Operation timed out after 59726 milliseconds with 69664108 out of 2606545925 bytes received
Trying to get layer on 52.5.185.86...
curl: (28) Operation timed out after 59682 milliseconds with 68287852 out of 2606545925 bytes received
Trying to get layer on 52.20.146.203...
curl: (28) Operation timed out after 59733 milliseconds with 68025708 out of 2606545925 bytes received
Trying to get layer on 34.200.28.105...
curl: (28) Operation timed out after 58846 milliseconds with 70843756 out of 2606545925 bytes received
Trying to get layer on 34.225.121.244...
curl: (28) Operation timed out after 59136 milliseconds with 110237399 out of 2606545925 bytes received
Trying to get layer on 54.152.209.167...
curl: (28) Operation timed out after 59669 milliseconds with 67829100 out of 2606545925 bytes received
```

**Comment by FRosner** [comment] 2017-10-26 12:34
I'm having the same issue. Happens on multiple machines.

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:40:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:40:33 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
Sending build context to Docker daemon 67.68 MB

Step 1/15 : FROM java:8

8: Pulling from library/java

5040bd298390: Pulling fs layer

fce5728aad85: Pulling fs layer

76610ec20bf5: Pulling fs layer

60170fec2151: Pulling fs layer

e98f73de8f0d: Pulling fs layer

11f7af24ed9c: Pulling fs layer

49e2d6393f32: Pulling fs layer

bb9cdec9c7f3: Pulling fs layer

60170fec2151: Waiting

e98f73de8f0d: Waiting

11f7af24ed9c: Waiting

bb9cdec9c7f3: Waiting

49e2d6393f32: Waiting

fce5728aad85: Verifying Checksum

fce5728aad85: Download complete

60170fec2151: Verifying Checksum

60170fec2151: Download complete

76610ec20bf5: Verifying Checksum

76610ec20bf5: Download complete

e98f73de8f0d: Verifying Checksum

e98f73de8f0d: Download complete

11f7af24ed9c: Verifying Checksum

11f7af24ed9c: Download complete

5040bd298390: Verifying Checksum

5040bd298390: Download complete

bb9cdec9c7f3: Verifying Checksum

bb9cdec9c7f3: Download complete

5040bd298390: Pull complete

fce5728aad85: Pull complete

76610ec20bf5: Pull complete

60170fec2151: Pull complete

e98f73de8f0d: Pull complete

11f7af24ed9c: Pull complete

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by nandhini915** [comment] 2017-10-26 12:53
status.docker.com updated. 
https://app.status.io/dashboard/533c6539221ae15e3f000031/incidents

we've identified the issue and are working on remediating it.

**Comment by cyphar** [comment] 2017-10-26 15:07
I've noticed this when using [`skopeo`](https://github.com/projectatomic/skopeo) (as part of `umoci`'s test suite).

**Comment by nandhini915** [comment] 2017-10-26 15:15
We've identified and addressed the issue. We've been able to successfully download large layers on GCE engines in us-central-1. Could you let us know if you're still facing this issue?

**Comment by nickstenning** [comment] 2017-10-26 15:27
From where we're sitting it's certainly better but it's not fixed. Running the repro script from earlier in this thread in `us-central1-f` we still see the fetch stalling about half the time.

**Comment by nickstenning** [comment] 2017-10-26 15:35
It looked like half the time a few minutes ago but it might have got worse again. If it helps folks at AWS, here are some request IDs:

### failed/stalled

```
X-Amz-Cf-Id: FRLu-lzRdB9fILMcq6sQgULAn5lq3kIpU5ZR6kMQdHjxBtrk-UUEng==
X-Amz-Cf-Id: hujWIRYEwnb1234oaolebl2DNAYgL-sSeSAN7fNtrs5V7CfKUuRWOQ==
X-Amz-Cf-Id: hDlFtHOIugO0ThP9t_iJ7i1FIIaqz6677y9tvLNS5bM2QIPIQC9PAg==
X-Amz-Cf-Id: 7Cupgsz8wIYkeRC7h1Mjl5dxeoOPXLHjrYpN60ckSwrrTcruc6oAkA==
X-Amz-Cf-Id: GOj6pI9iz6bTbJrAMfArW-XKzs9J191UIoCPDrnp2rN4Jmiy5NUsOg==
X-Amz-Cf-Id: b-HlW9eW0OYQWj2LyYTpVB_cU7wQGmXTmq27zy31tpVSf20QbzjT1g==
```

### successful layer fetch

```
X-Amz-Cf-Id: m2HSSNzjPLdzN9Qt7msbgPsdyA9bC6RAxO_3gMokBYh5E_5sfNkr0Q==
X-Amz-Cf-Id: ZDCU-0i5HeGmuwCe-JyVDtSbEXDDPmdfkdQG30U8_X0qbE1SqLfKQA==
```

**Comment by nickstenning** [comment] 2017-10-26 16:09
I notice you've marked the issue as resolved on https://status.docker.com. Unfortunately we're still seeing frequent stalls. Here's one example:

```
root@instance-3:~# date
Thu Oct 26 16:04:38 UTC 2017
root@instance-3:~# curl -H'Metadata-Flavor: Google' http://metadata.google.internal/computeMe
tadata/v1/instance/zone; echo
projects/324134624646/zones/us-central1-f
root@instance-3:~# ./registryhang.sh
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.2
0.146.203...
* Connected to registry-1.docker.io (52.20.146.203) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=*.docker.io
*        start date: 2017-08-02 00:00:00 GMT
*        expire date: 2018-09-02 12:00:00 GMT
*        subjectAltName: registry-1.docker.io matched
*        issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*        SSL certificate verify ok.
> GET /v2/travisci/ci-amethyst/blobs/sha256:45464f14df488f191b61d8a409bed2139c88931f060ad70e5
89bbd10ba4ca3ee HTTP/1.1
> User-Agent: curl/7.35.0
> Host: registry-1.docker.io
> Accept: */*
> Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDTHpDQ0FkU2dBd0lCQ
WdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0Uk5Gb3pPa2RYTjBrNldGUlFSRHBJVFRSUk9rOVVWRm
c2TmtGRlF6cFNUVE5ET2tGU01rTTZUMFkzTnpwQ1ZrVkJPa2xHUlVrNlExazFTekFlRncweE56QTFNREl5TWpBME5UZGF
GdzB4T0RBMU1ESXlNakEwTlRkYU1FWXhSREJDQmdOVkJBTVRPMDFPTms0NlJraFVWenBKV0VWSE9rOUpOMUU2UVRWWFJq
cFpSRVUwT2pkRE4wNDZSMWRKVVRvMVZ6STNPa2hPTlVvNlZVNURRVG95U0UxQ01Ga3dFd1lIS29aSXpqMENBUVlJS29aS
XpqMERBUWNEUWdBRU5KRklhQ1hHNWYxSk9BZnZSaTJDU081K1Q5RVpKd2doai9SUXgzNW9Uc3Q4RnhXY0dRc3ZOMG5sdW
5DVVdIbENxN2I4NFJRTXV0WUVIUnY4MVhweTU2T0JzakNCcnpBT0JnTlZIUThCQWY4RUJBTUNCNEF3RHdZRFZSMGxCQWd
3QmdZRVZSMGxBREJFQmdOVkhRNEVQUVE3VFU0MlRqcEdTRlJYT2tsWVJVYzZUMGszVVRwQk5WZEdPbGxFUlRRNk4wTTNU
anBIVjBsUk9qVlhNamM2U0U0MVNqcFZUa05CT2pKSVRVSXdSZ1lEVlIwakJEOHdQWUE3VVRSYU16cEhWemRKT2xoVVVFU
TZTRTAwVVRwUFZGUllPalpCUlVNNlVrMHpRenBCVWpKRE9rOUdOemM2UWxaRlFUcEpSa1ZKT2tOWk5Vc3dDZ1lJS29aSX
pqMEVBd0lEU1FBd1JnSWhBSTJVUlpMQVRTM3R4bjNpNTY0SXVQSFEwQU1Mb1g5cTZCMmdnN01KSHJuTkFpRUE0Q3lzbmt
ENHhjQm42amdobVdnQzczQjdGVkszenFnOTV4ZjNRK2xGVHlrPSJdfQ.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b
3J5IiwibmFtZSI6InRyYXZpc2NpL2NpLWFtZXRoeXN0IiwiYWN0aW9ucyI6WyJwdWxsIl19XSwiYXVkIjoicmVnaXN0cn
kuZG9ja2VyLmlvIiwiZXhwIjoxNTA5MDM0MjI3LCJpYXQiOjE1MDkwMzM5MjcsImlzcyI6ImF1dGguZG9ja2VyLmlvIiw
ianRpIjoieWhURlRXb0xYNGJQc0YwZGl2LTAiLCJuYmYiOjE1MDkwMzM2MjcsInN1YiI6IiJ9.vV5SuLDBt7pQpMp4PXs
T_lKn7D8SMydkaYcm8M9vcqBO3W6svdqTssWVBXVcktpVnhmwDypAmtid85f_NWF3Vw
>
< HTTP/1.1 307 Temporary Redirect
< Content-Type: application/octet-stream
< Docker-Distribution-Api-Version: registry/2.0
< Location: https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/
45/45464f14df488f191b61d8a409bed2139c88931f060ad70e589bbd10ba4ca3ee/data?Expires=1509035127&S
ignature=O3xRi3092fakNCH31OQliN2zXIuLodaHHhzOqBsR4TFFyY2La5bachP0ZFL-qctbl6DH9Ea7QDjBCBeiefUm
~UDCpLl6sJ9i38RgIPoHVi3T~wesZBYEkY2qLbhiFB~UVa87b-uASYCg6LmlAtXhX2dXC~gGNDpP-wjOSprkdJ4_&Key-
Pair-Id=APKAJECH5M7VWIS5YZ6Q
< Date: Thu, 26 Oct 2017 16:05:27 GMT
< Content-Length: 432
< Strict-Transport-Security: max-age=31536000
<
* Ignoring the response-body
{ [data not shown]
100   432  100   432    0     0   3056      0 --:--:-- --:--:-- --:--:--  3063
* Connection #0 to host registry-1.docker.io left intact
* Issue another request to this URL: 'https://dseasb33srnrn.cloudfront.net/registry[35/22926]
/registry/v2/blobs/sha256/45/45464f14df488f191b61d8a409bed2139c88931f060ad70e589bbd10ba4ca3ee
/data?Expires=1509035127&Signature=O3xRi3092fakNCH31OQliN2zXIuLodaHHhzOqBsR4TFFyY2La5bachP0ZF
L-qctbl6DH9Ea7QDjBCBeiefUm~UDCpLl6sJ9i38RgIPoHVi3T~wesZBYEkY2qLbhiFB~UVa87b-uASYCg6LmlAtXhX2d
XC~gGNDpP-wjOSprkdJ4_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q'
* Hostname was NOT found in DNS cache
*   Trying 52.84.7.58...
* Connected to dseasb33srnrn.cloudfront.net (52.84.7.58) port 443 (#1)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: C=US; ST=Washington; L=Seattle; O=Amazon.com, Inc.; CN=*.cloudfront.net
*        start date: 2016-10-26 00:00:00 GMT
*        expire date: 2017-12-17 23:59:59 GMT
*        subjectAltName: dseasb33srnrn.cloudfront.net matched
*        issuer: C=US; O=Symantec Corporation; OU=Symantec Trust Network; CN=Symantec Class 3 Secure Server CA - G4
*        SSL certificate verify ok.
> GET /registry-v2/docker/registry/v2/blobs/sha256/45/45464f14df488f191b61d8a409bed2139c88931f060ad70e589bbd10ba4ca3ee/data?Expires=1509035127&Signature=O3xRi3092fakNCH31OQliN2zXIuLodaHHhzOqBsR4TFFyY2La5bachP0ZFL-qctbl6DH9Ea7QDjBCBeiefUm~UDCpLl6sJ9i38RgIPoHVi3T~wesZBYEkY2qLbhiFB~UVa87b-uASYCg6LmlAtXhX2dXC~gGNDpP-wjOSprkdJ4_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q HTTP/1.1
> User-Agent: curl/7.35.0
> Host: dseasb33srnrn.cloudfront.net
> Accept: */*
> Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsIng1YyI6WyJNSUlDTHpDQ0FkU2dBd0lCQWdJQkFEQUtCZ2dxaGtqT1BRUURBakJHTVVRd1FnWURWUVFERXp0Uk5Gb3pPa2RYTjBrNldGUlFSRHBJVFRSUk9rOVVWRmc2TmtGRlF6cFNUVE5ET2tGU01rTTZUMFkzTnpwQ1ZrVkJPa2xHUlVrNlExazFTekFlRncweE56QTFNREl5TWpBME5UZGFGdzB4T0RBMU1ESXlNakEwTlRkYU1FWXhSREJDQmdOVkJBTVRPMDFPTms0NlJraFVWenBKV0VWSE9rOUpOMUU2UVRWWFJqcFpSRVUwT2pkRE4wNDZSMWRKVVRvMVZ6STNPa2hPTlVvNlZVNURRVG95U0UxQ01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRU5KRklhQ1hHNWYxSk9BZnZSaTJDU081K1Q5RVpKd2doai9SUXgzNW9Uc3Q4RnhXY0dRc3ZOMG5sdW5DVVdIbENxN2I4NFJRTXV0WUVIUnY4MVhweTU2T0JzakNCcnpBT0JnTlZIUThCQWY4RUJBTUNCNEF3RHdZRFZSMGxCQWd3QmdZRVZSMGxBREJFQmdOVkhRNEVQUVE3VFU0MlRqcEdTRlJYT2tsWVJVYzZUMGszVVRwQk5WZEdPbGxFUlRRNk4wTTNUanBIVjBsUk9qVlhNamM2U0U0MVNqcFZUa05CT2pKSVRVSXdSZ1lEVlIwakJEOHdQWUE3VVRSYU16cEhWemRKT2xoVVVFUTZTRTAwVVRwUFZGUllPalpCUlVNNlVrMHpRenBCVWpKRE9rOUdOemM2UWxaRlFUcEpSa1ZKT2tOWk5Vc3dDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBSTJVUlpMQVRTM3R4bjNpNTY0SXVQSFEwQU1Mb1g5cTZCMmdnN01KSHJuTkFpRUE0Q3lzbmtENHhjQm42amdobVdnQzczQjdGVkszenFnOTV4ZjNRK2xGVHlrPSJdfQ.eyJhY2Nlc3MiOlt7InR5cGUiOiJyZXBvc2l0b3J5IiwibmFtZSI6InRyYXZpc2NpL2NpLWFtZXRoeXN0IiwiYWN0aW9ucyI6WyJwdWxsIl19XSwiYXVkIjoicmVnaXN0cnkuZG9ja2VyLmlvIiwiZXhwIjoxNTA5MDM0MjI3LCJpYXQiOjE1MDkwMzM5MjcsImlzcyI6ImF1dGguZG9ja2VyLmlvIiwianRpIjoieWhURlRXb0xYNGJQc0YwZGl2LTAiLCJuYmYiOjE1MDkwMzM2MjcsInN1YiI6IiJ9.vV5SuLDBt7pQpMp4PXsT_lKn7D8SMydkaYcm8M9vcqBO3W6svdqTssWVBXVcktpVnhmwDypAmtid85f_NWF3Vw
>
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< Content-Length: 2606545925
< Connection: keep-alive
< Date: Thu, 26 Oct 2017 14:59:38 GMT
< Last-Modified: Tue, 17 Oct 2017 15:21:46 GMT
< ETag: "34ad5209d0795bddca17190c95400243-78"
< Expires: Tue, 17 Oct 2017 15:51:45 GMT
< x-amz-version-id: M.CyFQnhdHMJ7Jbt1k7nQ9_nTi2rF6Ou
< Accept-Ranges: bytes
* Server AmazonS3 is not blacklisted
< Server: AmazonS3
< X-Cache: RefreshHit from cloudfront
< Via: 1.1 6abca978c7767ffcb2452cf2eadf7805.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: Nopsghkxruot3MXliP_L7vCMkEVTukzkv0sETe12N06I6V0rWF-ZAg==
<
{ [data not shown]
  9 2485M    9  247M    0     0  5117k      0  0:08:17  0:00:49  0:07:28     0^C
```

Thats a download that when interruppted had been running for 49 seconds and had downloaded 247M of the layer before stalling. The `0` before the `^C` is the current data rate, i.e. zero when interrupted.

**Comment by nandhini915** [comment] 2017-10-26 16:10
Thanks for highlighting this and adding info. We will follow up.

**Comment by nickstenning** [comment] 2017-10-26 16:43
Just to update that as of a few minutes ago I can't reproduce a stall any more. 🎉

**Comment by tiffanyfj** [comment] 2017-10-26 19:26
@nandhini915, what was done to resolve the issue? Thanks.

**Comment by jpetazzo** [comment] 2017-10-27 11:07
My understanding is that there was an issue localized with a few CloudFront endpoints. As far as I know, we're waiting for more information from AWS to know what happened, and more importantly, how to detect it earlier in the future.

If, like most folks on this thread, you or your organization are critically relying on the Docker Hub for your operations, I **strongly recommend** _(can I get one of these <blink> tags from 1995, yo?)_ that you deploy a registry mirror. This will:

- significantly reduce your reliance on the network path between you and the Docker Hub (including CloudFront and whatever Docker Hub might be using in the future),
- significantly reduce your bandwidth costs (and Docker Inc.'s 👼 ),
- significantly improve the performance of your `docker pull` operations,
- be very easy to setup.

You can see how to setup a registry mirror (and configure your Docker Engines to use it) [in this recipe](https://docs.docker.com/registry/recipes/mirror/) and quite frankly I was shocked to see how ridiculously easy it is (honest!)

With ❤️ ,

You friendly 🐳📦 👨‍🏫

**Comment by nickstenning** [comment] 2017-10-27 11:47
@jpetazzo Thanks for following up to provide some more details, and thank you more generally for your help escalating this issue yesterday. ❤️ 

It's not immediately clear from the docs whether the registry mirror in pass-through cache mode supports forwarding credentials from its clients to the upstream mirror. Do you happen to know if it does, as that would be essential in a CI environment such as Travis?

**Comment by kizbitz** [comment] 2017-10-30 19:57
Closing...

**Closed by kizbitz** 2017-10-30 19:57 UTC

**Comment by zanes2016** [comment] 2018-02-06 18:30
It seems that this issue has resurfaced: travis-ci/travis-ci#9127 

We're also experiencing this issue intermittently with our private Docker Hub repo on AWS (oregon and n. california regions). We have a large layer of ~1.5GB

**Comment by mikeguidry** [comment] 2019-05-27 00:02
https://pastebin.com/jWNbhUBd - is an office moby script modified to resume ... you can change the initial bandwidth at the beginning (its 8 here.. i am downloading lots of stuf on spotty  connection over time).. or you can just set to 9999.. anyways
the original would hit the header saving to the final file name thus ruining -C (resume).. and if your connection is as bad as mine, then it would fail with 403 after awhile (token expired) so this does a loop and solves that..
I don't take credit or care.. its a mod to the official script which works for me. :) hope it helps someone else as much as it did for me..
