### ISSUE TITLE
Adult Content in comments

### ISSUE THREAD

**Issue by rickalm** [docker/hub-feedback#1178] opened 2017-09-21 16:24 UTC
The comment system does not provide a way to report in-appropriate content and in the last month the number of links to inappropriate content has been on the rise.

I have had to advise several schools to block access to the Docker Hub web site because there is no easy way to report these issues as they are discovered. Quay.IO seems to have a better approach to this issue

**Comment by nandhini915** [comment] 2017-09-22 15:55
Hi @rickalm - thanks for notifying us about this issue. We're actively trying to prune any adult content and working on a longer term solution. We've cleaned up a bunch of these already.

Are there specific images you've come across that have adult content in their comments?

**Comment by cswarth** [comment] 2017-09-26 17:04
> We're actively trying to prune any adult content and working on a longer term solution. 

I'm sorry to have to point this out, but you're just blowing smoke -  you're not seriously looking for links to adult content.  If you were you would have addressed several polluted comments already mentioned in #1152 

https://hub.docker.com/r/_/busybox/ 
https://hub.docker.com/_/maven/
https://hub.docker.com/r/puppet/facter/
https://hub.docker.com/r/nginxdemos/hello/

@bmitch3020 even provided a google search to identify repos polluted by one prolific spammer,
https://www.google.com/search?q=caramembuatwebsite+site%3Ahub.docker.com&ie=utf-8&oe=utf-8

This isn't something you guys need to debate.  Spammers are making a mess of your site, dockerhub is becoming a porn and spam haven, and there is apparently no will to clean it up.  
Just delete the comments feature and be done with.

**Comment by atomheartmother** [comment] 2017-09-27 00:33
I noticed this again today under the official MongoDB container. I reported the link to Google and it's been removed now. I also notice that the post on Docker Hub has been removed as well.

**Comment by perryprog** [comment] 2017-10-04 18:36
Should probably close this, as it's a dupe of #1152.

**Comment by nandhini915** [comment] 2017-10-06 02:05
FYI - spam comments have been removed, and the spammers deactivated.

**Comment by tianon** [comment] 2018-01-02 23:52
The "Comments" functionality appears to now be completely gone from Docker Hub, which renders this issue obsolete! :tada: :heart:

**Closed** 2018-04-26 22:02 UTC

**Comment by seema9876** [comment] 2023-12-05 11:54
Your Chandigarh escort will meet on decided time at your specified location, welcoming you with a friendly smile and utmost courtesy.
[](http://www.chandigarhescortservice.com/)
<a href="http://www.chandigarhescortservice.com/zirakpur-escorts.html">Zirakpur Escorts Service</a>
