### ISSUE TITLE
Pushed images not displayed in web ui

### ISSUE THREAD

**Issue by wlad** [docker/hub-feedback#2145] opened 2021-08-30 23:05 UTC
## Problem description

Recently pushed images do not appear in the web ui. I pushed several images today (some from local, some from Github Actions) und everything worked fine. But since a few hours I can't push anything even if I create a repo via the web ui. Is it possible that some service are not fully operational although everything seems green on [status page]?(https://status.docker.com/)

![image](https://user-images.githubusercontent.com/64201310/131416289-e675241c-6f8d-415d-b639-aaea357b5cf6.png)

https://user-images.githubusercontent.com/64201310/131416645-47e88a4c-9e52-4fa0-9772-ece94ac35994.mp4

https://user-images.githubusercontent.com/64201310/131416653-26058b51-bccf-4b4f-8da0-8a5a83847889.mp4

**Comment by mikeparker** [comment] 2021-08-30 23:22
I can reproduce this, taking a look now

**Comment by mikeparker** [comment] 2021-08-30 23:34
There's something up with the web UI - looks like pushing / pulling from the registry itself is intact though, and its just the online view, can you confirm?

**Comment by mikeparker** [comment] 2021-08-31 00:08
Thanks for reporting, this is a live incident, updates will be posted here https://docker.status.io/

**Comment by shawnaxsom** [comment] 2021-08-31 01:32
We've pushed out a fix. Events are being processed, the system is catching up, and you might see a little latency while it's processing.

**Comment by shawnaxsom** [comment] 2021-08-31 01:55
The events have finished processing, and it looks like your user page has updated images now.

Closing, but let us know if you have any further related issues. Thanks for reporting!

**Comment by shawnaxsom** [comment] 2021-08-31 01:56
https://docker.status.io/ will be updated with the latest status.

**Closed by shawnaxsom** 2021-08-31 01:55 UTC

**Comment by wlad** [comment] 2021-08-31 09:20
thanks, I'm going to retry everything today.

How can one actually jump from https://status.docker.com/ to the [historical data view](https://status.docker.com/pages/history/533c6539221ae15e3f000031). There seem to be no working link on the status page(?)
