### ISSUE TITLE
Using personal access token with Dockerhub API Beta

### ISSUE THREAD

**Issue by qbiqing** [docker/hub-feedback#2127] opened 2021-07-23 09:13 UTC
## Problem description

When trying to use the Dockerhub beta API, such as this endpoint: `/v2/namespaces/{namespace}/repositories/{repository}/images`,

 I used the authentication method through Personal Access Tokens as introduced in the [docs](https://docs.docker.com/docker-hub/api/latest/#tag/access-tokens). That is, I created a JWT using the authentication endpoint in this [section](https://docs.docker.com/docker-hub/api/latest/#tag/authentication) and with the personal access token instead of the password in the password field. I was able to get a JWT in return, however, when I use it to get details about the images, I got this error:

```
{
    "message": "access to the resource is forbidden with personal access token"
}
```
I'm confused if the personal access token is an acceptable mode of authentication? This is not clear in the docs.

**Comment by mikeparker** [comment] 2021-07-23 15:40
Apologies, that sounds like a gap in the docs. PATs are not currently supported for API operations, but this is something we are looking to implement in future.

**Comment by qbiqing** [comment] 2021-07-26 01:54
@mikeparker thanks, good to know! It would be really useful for apps using the Dockerhub API.

**Comment by qbiqing** [comment] 2021-07-30 02:45
To add on, the docs now are even more misleading, because this is under the section of "Create an authentication token":
![image](https://user-images.githubusercontent.com/27569398/127592006-30c727ac-fe1d-43ab-b370-a866149b714d.png)
It says PAT can be used to authenticate with but I still get forbidden access to resource.

**Comment by mikeparker** [comment] 2021-07-30 10:28
@qbiqing you're absolutely right, the docs are misleading here. I'll get this fixed. Sorry again.

**Comment by modem7** [comment] 2021-08-14 23:08
> Apologies, that sounds like a gap in the docs. PATs are not currently supported for API operations, but this is something we are looking to implement in future.

I thought that https://github.com/docker/roadmap/issues/115 was rolled out for this purpose?

**Comment by modem7** [comment] 2021-08-31 12:36
Is there any updates on this?

There doesn't seem to be much of a point to 2fa if you're unable to upload something as simple as a readme file.

**Comment by srbala** [comment] 2021-09-19 06:25
> PATs are not currently supported for API operations, but this is something we are looking to implement in future.
@mikeparker Any tentative timeline for this to be implemented

**Comment by modem7** [comment] 2022-03-19 00:19
Stalebot bump

**Comment by technicallyjosh** [comment] 2022-03-19 17:14
I think something to help this confusion on the error message is to return something like "access to the resource is forbidden with an access token generated from a PAT". As far as the API access, this was bumped my way and should be fairly simple to patch in since it *is* a repo scoped call. (Right now PATs only have repo scopes)

**Comment by technicallyjosh** [comment] 2022-03-19 18:38
I've opened a PR to allow for image management route usage with PAT generated JWTs in our APIs. We can address the verbiage on the 403 this week.

**Comment by technicallyjosh** [comment] 2022-03-29 18:44
👋🏼 You can now use a properly scoped JWT generated from a PAT on these image management routes. Changes to the wording should be updated within the next week.

**Comment by technicallyjosh** [comment] 2022-03-29 19:02
I'll close this out. Thank you for leaving the feedback! Sorry it took a while to get to!

**Comment by modem7** [comment] 2022-06-02 14:52
> 👋🏼 You can now use a properly scoped JWT generated from a PAT on these image management routes. Changes to the wording should be updated within the next week.

Heya @technicallyjosh

Lots of people are still having issues with this. 

Do you have a link to the appropriate documentation to get this to work as intended? 

Thanks!

**Comment by christian-korneck** [comment] 2022-06-11 01:39
@technicallyjosh Thanks for this. Unfortunately I don't seem to be able to get this to work.

What I try is:
- generate JWT for PAT (GET `/v2/users/login`) - works
  - note: the PAT has `repo:admin` scope
- try to update a repo description (use JWT as bearer token for PATCH `/v2/repositories/my-user/my-repo/`)

Result is a 403 FORBIDDEN with message:
```
access is forbidden with a JWT issued from a personal access token
```

Am I doing anything incorrectly? Would appreciate any pointer into the right direction. Thanks a lot in advance!

**Comment by technicallyjosh** [comment] 2022-06-11 01:59
@modem7 @christian-korneck Hey thanks for the ping on this not working still. It seems we might have some sort of regression here. I do know we've been slaying tech debt and moving APIs around specifically with registry/repos, so I'm wondering if something got lost in translation behind the scenes. I'll have some bandwidth to look at this this weekend and early next week and keep you updated.

**Comment by technicallyjosh** [comment] 2022-06-12 01:02
Okay so it seems like there were some routes missed such as the one you mentioned: `PATCH /v2/repositories/{namespace}/{repo}`. I'll put a PR in to see if I can get the rest of these to work with the tokens.

**Comment by technicallyjosh** [comment] 2022-06-14 18:28
👋🏼 These fixes are now live on production. Let us know if there are any issues 😄.

**Closed by technicallyjosh** 2022-06-14 18:28 UTC
Labels: bug, enhancement

**Comment by christian-korneck** [comment] 2022-06-14 20:09
@technicallyjosh thanks *a lot* for looking into this so quickly, much appreciated!

Unfortunately I still don't seem to get my use case to be working. Here's what I do:

1.) create a PAT via the DockerHub WebUI with `read, write, delete` scope.
2.) generate JWT. The password is a personal access 
```
curl --location --request POST 'https://hub.docker.com/v2/users/login' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data-raw '{
  "username": "my-docker-username",
  "password": "00000000-0000-0000-0000-000000000000"
}'
```

the result body contains a JWT in the style of
```
{"token":"ey...pg"}}
```

3.) Use the token in a request to update a repo's description:

```
curl --location --request PATCH 'https://hub.docker.com/v2/repositories/job314/helloo/' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer ey...pg' \
--data-raw '{
  "description": "Hello World!"
}'
```

The result is a 403 FORBIDDEN:
```
{
    "detail": "access is forbidden with a JWT issued from a personal access token"
}
```

(The same example works if I use a password to create the JWT instead of a PAT)

Do you have any idea what I might be doing wrong? I highly appreciate any pointer into the right direction. (I assume it must be some stupid mistake on my side)?

Again, thanks a lot for your time and efforts!!

**Comment by modem7** [comment] 2022-06-15 00:42
> Of course! The JWT generation is fine.
> 
> Interesting... I'll have to look into that as I know I allowed the PATCH to be used with a PAT generated token. It's possible that that route is going to a service that I was not aware of (we are migrating from an older service and it may still be used there).

Heya,

Would it make sense keeping this issue open until we can do community verification that all works as expected?

**Comment by zigarn** [comment] 2022-07-03 10:54
Hi @technicallyjosh, any news about the problem raised by @christian-korneck (https://github.com/docker/hub-feedback/issues/2127#issuecomment-1155664799) that is still existant.
It is generating failure in CI jobs trying to update repo's description.

**Comment by zappy-shu** [comment] 2022-07-13 12:59
Good afternoon @https://github.com/zhangguanzhang 

We are rolling out personal access token support across endpoints as we speak. The PATCH repository endpoint was rolled out today with support for `admin` scoped PATs. Could you ensure your PAT has `admin` scope and test again for me?

Thanks

**Comment by zhangguanzhang** [comment] 2022-07-13 13:47
> Good afternoon @zhangguanzhang
> 
> We are rolling out personal access token support across endpoints as we speak. The PATCH repository endpoint was rolled out today with support for `admin` scoped PATs. Could you ensure your PAT has `admin` scope and test again for me?
> 
> Thanks

![image](https://user-images.githubusercontent.com/18641678/178748707-e04eb866-a690-481b-8984-bf22e48a1043.png)
I used the `Read, Write, Delete`, but does not work for me.
```
repo_user=zhangguanzhang
repo_token=xxx-xxx-xxx-xxx-xxx
token=$(curl -s -H "Content-Type: application/json" -X POST \
    -d '{"username": "'${repo_user}'", "password": "'${repo_token}'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
$ curl -iLH "Authorization: Bearer ${token}" -X DELETE https://hub.docker.com/v2/repositories/zhangguanzhang/xxx/tags/test
{"detail": "access is forbidden with a JWT issued from a personal access token"}
# or used the jwt
$ curl -iLH "Authorization: JWT ${TOKEN}" -X DELETE https://hub.docker.com/v2/repositories/zhangguanzhang/xxx/tags/test
{"detail": "access is forbidden with a JWT issued from a personal access token"}
```
if I used the password for `repo_token`, It works

**Comment by zhangguanzhang** [comment] 2022-07-13 13:56
> @zhangguanzhang could you do a verbose curl and list the response headers for me? And give me the time/date that you make the call. Thank you

I updated the previous comment with more details

**Comment by zhangguanzhang** [comment] 2022-07-13 14:15
> @zhangguanzhang that appears to be a `DELETE tag` operation rather than a `PATCH repo`. Deleting a tag has not yet been migrated over so does not currently have PAT support (it's next on the list). Does `PATCH repo` work for you now?

How to delete a tag use the api 😢,I just want to delete a tag

**Comment by zappy-shu** [comment] 2022-07-13 14:19
@zhangguanzhang unfortunately for now you would have to use a password. I will prioritize getting the DELETE tag flow migrated over to use the new authentication flows and support PATs ASAP. Sorry for the inconvenience

**Comment by zappy-shu** [comment] 2022-07-13 14:24
@zigarn that's correct. URL data encoding is no longer supported. If this is a feature you want please could you open a new ticket? This one is getting a little full. Thanks

**Comment by zigarn** [comment] 2022-07-13 14:25
@zappy-shu It's OK for me, just need to update https://circleci.com/developer/orbs/orb/circleci/docker#commands-update-description

**Comment by christian-korneck** [comment] 2022-07-13 21:17
@zappy-shu thanks 🙇  a lot also for this also from my side! Updating the repo settings now seems to work fine. 🚀  (At a first look my ["Docker Push Readme"](https://github.com/christian-korneck/docker-pushrm) Tool now seems to work with PATs without any change necessary). 

Btw. I didn't need to create an `admin` scope PAT. Creating a `read/write` PAT from the Docker Hub WebUI seems to be sufficient.

**Comment by reitzig** [comment] 2023-07-02 20:06
Extending on what @zigarn posted (thank you!), I needed to upload Markdown instead of a file name. I _used_ to use this:

```bash
curl -siX PATCH "https://hub.docker.com/v2/repositories/${dh_repo}/" \
     -H "Authorization: JWT ${dh_token}" \
     -o "${CURL_OUT}" \
     --data-urlencode description="${gh_description}" \
     --data-urlencode full_description@"${readme_profile_filepath}"
```

which does not work anymore. _Now_ I need to encode the file content as JSON:

```bash
curl -siX PATCH "https://hub.docker.com/v2/repositories/${dh_repo}/" \
     -H "Authorization: JWT ${dh_token}" \
     -H "Content-Type: application/json" \
     -o "${CURL_OUT}" \
     --data @- << PAYLOAD
{
    "description": "${gh_description}",
    "full_description": $(jq -Rsa . "${readme_profile_filepath}")
}
PAYLOAD
```

Credits for the usage of `jq`: [SO#50380697](https://stackoverflow.com/a/50380697/539599)
