### ISSUE TITLE
"incorrect username or password" on automated build

### ISSUE THREAD

**Issue by mikew** [docker/hub-feedback#630] opened 2016-03-31 21:40 UTC
Did an automated build 3 days ago and it worked fine. Pushed some code today and:

<img width="1008" alt="screen shot 2016-03-31 at 6 39 15 pm" src="https://cloud.githubusercontent.com/assets/4729/14191729/ebbced8e-f76f-11e5-9ece-03c7342ce8df.png">

**Comment by MinnSoe** [comment] 2016-03-31 23:11
I have the same issue too. Re-triggering doesn't seem to do it either.

    Starting to clone
    Cloning into '.'...
    Cloning done
    Starting Build
    KernelVersion: 3.13.0-40-generic
    Os: linux
    BuildTime: 2016-02-22T21:37:01.910365059+00:00
    ApiVersion: 1.22
    Version: 1.10.2
    GitCommit: c3959b1
    Arch: amd64
    GoVersion: go1.5.3
    Starting build of index.docker.io/minn/jekyll-gen:buildpack...
    Step 1 : FROM ruby:2.3
    Get https://registry-1.docker.io/v2/library/ruby/manifests/2.3: unauthorized: incorrect username or password

**Comment by pchico83** [comment] 2016-04-01 10:24
Is this in Docker Hub or in Docker Cloud?

**Comment by MinnSoe** [comment] 2016-04-01 12:44
@pchico83, for me, it's on the Docker Hub. [Example](https://hub.docker.com/r/minn/jekyll-gen/builds/bzkbufma8qi3b2yvukfw6oq/).

Changing the tag from `:2.3` to `:latest` seemed to make it move along, however I'm not sure how correlated it is.

**Comment by mikew** [comment] 2016-04-01 12:47
@pchico83 Same for me, was on [Docker Hub](https://hub.docker.com/r/mikewhy/docker-gen-letsencrypt/builds/bkakwpartm8w3y4njrykxh4/). FWIW, changing nothing and just waiting solved it for me.

**Comment by pchico83** [comment] 2016-04-01 13:23
Looks like there was a temporal issue with credentials in hub yesterday.
Please, let us know if it happens again

**Comment by guss77** [comment] 2016-04-12 05:51
This happens again now. It happens sporadically. Logging in with some user solves the problem for me, as well as waiting/recreating the build agent (the build agent is running on an EC2 on demand instance).

This happens to me every few days, when pulling public images. I shouldn't need to have a login for that.

**Comment by hongymagic** [comment] 2016-05-22 23:10
Still happening for me too:

```
Step 1 : FROM php:5.6-apache
Get https://registry-1.docker.io/v2/library/php/manifests/5.6-apache: unauthorized: incorrect username or password
```

**Comment by peco8** [comment] 2016-05-23 01:41
Same here

**Comment by barberj** [comment] 2016-05-23 01:54
me as well `Get https://registry-1.docker.io/v2/library/ruby/manifests/2.3.0: unauthorized: incorrect username or password`

**Comment by dennis-tra** [comment] 2016-05-24 04:39
for me as well with
`Get https://registry-1.docker.io/v2/library/ruby/manifests/2.3: unauthorized: incorrect username or password`

**Comment by bmleshopventory** [comment] 2016-05-24 04:44
Getting the same right now: 

Build failed: Get https://registry-1.docker.io/v2/shopventory/shopventory-base/manifests/latest: unauthorized: incorrect username or password

**Comment by peco8** [comment] 2016-05-24 04:52
I actually deleted my public repo on Dockerhub, and auto-built it again. Now it works.
Hope it helps!!

**Comment by bmleshopventory** [comment] 2016-05-24 05:19
My repo is private

**Comment by EpicJhon** [comment] 2016-05-24 05:37
I had the same problem docker hub. Apparently you have to re-login on web, I assume it must be a cookie that expires but the system continues to show the user in.

**Comment by davefinster** [comment] 2016-05-24 05:47
Same here:
Build failed: Get https://registry-1.docker.io/v2/mhart/alpine-node/manifests/latest: unauthorized: incorrect username or password
I'm a private repo and they're public.

**Comment by j0hnsmith** [comment] 2016-05-24 05:58
Just happened to me on an automated build, everything is public. I tried logging out of https://hub.docker.com and back in but it didn't help.

**Comment by typhoonzero** [comment] 2016-05-24 06:16
Same here:
Build failed: Get https://registry-1.docker.io/v2/typhoon1986/storm-docker/manifests/latest: unauthorized: incorrect username or password
Using dockerhub + github, repo is public

**Comment by EpicJhon** [comment] 2016-05-24 06:20
now get this error:

Build failed: Get https://registry-1.docker.io/v2/library/php/manifests/5.6-apache: unknown: too many failed login attempts for username or IP address

Using dockerhub + github, repo is public

**Comment by jaichopra** [comment] 2016-05-24 06:31
Getting this error now attempting to get ubuntu:14:04

**Comment by fskreuz** [comment] 2016-05-24 06:39
```
Step 1 : FROM php:5.6-cli
Get https://registry-1.docker.io/v2/library/php/manifests/5.6-cli: unknown: too many failed login attempts for username or IP address
```
hub repos all public

**Comment by davefinster** [comment] 2016-05-24 07:17
Just got this from Docker support:
"Hi davefinster,

We had problems earlier with our registry authentication service earlier due to the authentication service database being overwhelmed by a database backup operation. We killed that back up job and the authentication service has become operational again.

The impact this service disruption would include failure to push/pull images as well as failure of automated builds on both Docker Hub and Docker Cloud. For automated builds, our engineers has retriggered all impacted builds and they should be rebuilding as of now.

We sincerely apologize for the inconvenience. Please do let us know if you are still seeing issues with registry authentication."

**Comment by marcusmartins** [comment] 2016-06-02 05:38
For the latest authentication issues in this ticket - we had an intermittent  replication issue starting that impact how our build system authenticate with our repository service, the issue was fixed around May 23 23:30 PDT (May 24 6:30 UTC).

Closing this issue as we have quite a few timelines mixed up. Please open a new issue if you are experiencing authentication issues with auto builds as they probably not related to the original report.

@mikew Can you reopen if you're still experiencing the issue you reported?

**Closed by marcusmartins** 2016-06-02 05:38 UTC

**Comment by barberj** [comment] 2016-06-04 11:26
I'm still experiencing. I'll open a new ticket

**Comment by pablofmorales** [comment] 2016-06-11 22:11
Just do 

```
docker login

```

**Comment by guss77** [comment] 2016-06-11 22:15
@pablofmorales - the problem is that we're trying to use anonymous access to public resources. `docker login` is not an option.

**Comment by pablofmorales** [comment] 2016-06-11 22:16
worked for me.

**Comment by marcusmartins** [comment] 2016-06-13 16:25
If you are having issues with login, please open a new issue. I am locking this issue for comments for now.
