### ISSUE TITLE
Automated build failed to push

### ISSUE THREAD

**Issue by nikhilvs** [docker/hub-feedback#466] opened 2015-11-16 15:18 UTC
Push failed: {"errorDetail":{"message":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/84/84bde4d9092e2f25d39353ca703fc1a04f5b1ddf1db0a5551ce2dc31ce336e15/data?Expires=1447686622\u0026Signature=AGjWcLOU5F~jG0DlG5M6uavMoptp-ez99U57WswzsVAipP34Mmc5YWHarhHpKHxcOxsVtq4hK5gAFYksGc5lhZEkr474twLyS9FiNwApyimKrykQObD2-FMQ0A6uA0cZznY1jAjZ7dc6yR0PNyjU-p-ycDLE9hDCIRsjUQVXGW0_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.101.80:443: i/o timeout"},"error":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/84/84bde4d9092e2f25d39353ca703fc1a04f5b1ddf1db0a5551ce2dc31ce336e15/data?Expires=1447686622\u0026Signature=AGjWcLOU5F~jG0DlG5M6uavMoptp-ez99U57WswzsVAipP34Mmc5YWHarhHpKHxcOxsVtq4hK5gAFYksGc5lhZEkr474twLyS9FiNwApyimKrykQObD2-FMQ0A6uA0cZznY1jAjZ7dc6yR0PNyjU-p-ycDLE9hDCIRsjUQVXGW0_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.101.80:443: i/o timeout"}
SourceRef

**Comment by kentmw** [comment] 2015-11-16 16:04
+1 this is happening to me too

**Comment by arnaud-deprez** [comment] 2015-11-16 19:16
+1 Same for me. https://hub.docker.com/r/arnaudeprez/activemq/builds/ba7z38upduw4pqkyeckkfqz/

**Comment by mrbobbytables** [comment] 2015-11-16 21:25
+1 same issue for me with a good chunk of my containers. latest example:
https://hub.docker.com/r/mrbobbytables/chronos/builds/buhbvqwoyjrcquvwdj3vy7e/

**Comment by matthewwiggins** [comment] 2015-11-16 22:57
+1, been failing all day with the same timeout.

**Comment by angelrr7702** [comment] 2015-11-17 02:31
the same for me .. for some reason fail to build any of my container ..  user: angelrr7702  organization: quantumobject

**Comment by mghazizadeh** [comment] 2015-11-17 05:10
The root cause of this is intermittent push issues on the registry in general. Our engineering and infrastructure team is diligently working on it.

**Comment by matthewwiggins** [comment] 2015-11-17 06:45
@mghazizadeh thanks for the update.

**Comment by xbglowx** [comment] 2015-11-17 06:52
@matthewwiggins what is your output from:

`telnet 54.192.101.80 443`

**Comment by matthewwiggins** [comment] 2015-11-17 06:57
```telnet 54.192.101.80 443
Trying 54.192.101.80...
Connected to server-54-192-101-80.iad2.r.cloudfront.net.
Escape character is '^]'.
Connection closed by foreign host.```

**Comment by xbglowx** [comment] 2015-11-17 07:57
@matthewwiggins thanks for the output, but forgot you mentioned this is for autobuild, which has nothing to do with your localhost.

We are still actively working on this issue.

**Comment by matthewwiggins** [comment] 2015-11-17 08:05
NP, that thought did occur to me afterwards. Local pushes continue to be fine.

**Comment by oryband** [comment] 2015-11-17 08:29
After #465 looks like to be resolved, we are now dealing with this problem as well. Still no automated builds for my organization.

**Comment by heyman** [comment] 2015-11-17 08:34
I've had this problem the last 15 hours. Would love to see it resolved.

**Comment by oryband** [comment] 2015-11-17 08:37
@avivl @doodyparizada @gadisr @fuzzyami @liorama @bolshoy

**Comment by mghazizadeh** [comment] 2015-11-17 08:49
We understand and apologize. We are working on addressing it. The two issues are unrelated. The push issue (here) seems related to networking infrastructure, but we will stay on it till it's resolved.

**Comment by clkao** [comment] 2015-11-17 09:03
This appears to be caused by a mix of Content-Length and (possibly involuntary) Connection: keep-alive headers in the HEAD request.

If you do `curl -X HEAD -D - <url> with the url in the original message, curl actually hangs with keep-alive.  `curl -H 'Connection: close' -X HEAD -D - ...` does close with a message: curl: (18) transfer closed with 146 bytes remaining to read.

**Comment by iolufemi** [comment] 2015-11-17 10:41
+1

**Comment by jfisbein** [comment] 2015-11-17 11:12
Same problem for me.

https://hub.docker.com/r/jfisbein/docker-images/builds/bjff4dxbjtbq3xompgytfvv/

**Comment by Opiumozor** [comment] 2015-11-17 11:29
+1

**Comment by rippinrobr** [comment] 2015-11-17 13:06
Had the "Authentication is required"  error and now I have this error: 

Push failed: {"errorDetail":{"message":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/7c/7c1dfc0ca7b5fbac3c4ed6fb443973b18e4922cff3f5050d52febc7284a74d2d/data?Expires=1447766325\u0026Signature=hXfGoZmHcUA9MieUBaIvPvUgqepausthesCOpwXDvTGWZu2OObYFDu3RvxmicT~XhYBe4f-76cnctcyedvie55ZYUDT0GZ-4IeVLUaN-EBopcRF650rcmYPUiLXq7Yrc6Vflek~EE8KLePlApz7PFSuFMyyoXMgSeSyfe6JK1sg_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.240.160.151:443: i/o timeout"},"error":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/7c/7c1dfc0ca7b5fbac3c4ed6fb443973b18e4922cff3f5050d52febc7284a74d2d/data?Expires=1447766325\u0026Signature=hXfGoZmHcUA9MieUBaIvPvUgqepausthesCOpwXDvTGWZu2OObYFDu3RvxmicT~XhYBe4f-76cnctcyedvie55ZYUDT0GZ-4IeVLUaN-EBopcRF650rcmYPUiLXq7Yrc6Vflek~EE8KLePlApz7PFSuFMyyoXMgSeSyfe6JK1sg_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.240.160.151:443: i/o timeout"}

Starting Day two of not being able to do automated builds.  Any kind of timeframe on a fix for this one?

**Comment by christoph-hipp** [comment] 2015-11-17 13:40
Dear Sirs,

since recently we are encountering errors in automated build repositories. The build completes, when the image gets pushed to the repository, the push seems to time out:

Push failed: {"errorDetail":{"message":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/1d/1dfefe48b93b2e79427899e2141b53b91421c3c7c67487ddb87f5341998ea2bc/data?Expires=1447767419\u0026Signature=ECtahpcokJ4nHId1shHYulOsJXy4kBPmmY77qUGdlDq8mDao5KlcOUuugx5FORNesw6gbOhgjU4vNFUgMmw8KWW9slENyOKkGNF-r0pZhO9VzW9YN95jaLR0U8Ynh6GK-CLANnXOmiQroHjHPjIozWxxdqltg6bPmaAPPHKTWz4_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.240.160.205:443: i/o timeout"},"error":"Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/1d/1dfefe48b93b2e79427899e2141b53b91421c3c7c67487ddb87f5341998ea2bc/data?Expires=1447767419\u0026Signature=ECtahpcokJ4nHId1shHYulOsJXy4kBPmmY77qUGdlDq8mDao5KlcOUuugx5FORNesw6gbOhgjU4vNFUgMmw8KWW9slENyOKkGNF-r0pZhO9VzW9YN95jaLR0U8Ynh6GK-CLANnXOmiQroHjHPjIozWxxdqltg6bPmaAPPHKTWz4_\u0026Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.240.160.205:443: i/o timeout”}

This happens with most of the automated builds, even though one or two seems to complete now and then.

We have repos that are failing constantly since a day. We can give you details per email if required.

Since the issue prevents us to deploy new software, there is some urgency to it. Please advise how this can be resolved.

**Comment by xbglowx** [comment] 2015-11-17 14:11
Hi all, thanks for the output. We are actively working on this issue.

**Comment by Hildebrand** [comment] 2015-11-17 14:53
+1

**Comment by mghazizadeh** [comment] 2015-11-18 09:14
builds should be working now as we have switched backends due to networking issues, but we are still working this to resolve the original root cause.

**Comment by oryband** [comment] 2015-11-18 10:27
this was resolved for us as well. 2-day outage. outrageous.

**Comment by mghazizadeh** [comment] 2015-12-03 08:18
we have published a post mortem for the service degradation on Nov 16th - 17th.. https://forums.docker.com/t/post-mortem-for-docker-hub-automated-build-issue-nov-16th-nov-17th/4790

**Comment by sexdon** [comment] 2015-12-21 07:54
+1 

Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/5f/5fb10c5df8aba62d415999f0576a083084dc13b83b7ff28a38b3545b244133ca/data?Expires=1450683368&Signature=NaLFVCjX9gCdj1DnzZ5N7apfACzubCeaMrbvhhXI~XAJkOVa-gFLFhHME05XV8wGht9ETQq5ZQQTo34wU5RmUlutX9TfVwe3W8DVDN9~xO1n4LOYB5qPENfEMTKvQLEK34TnF6AMnVX~cnKwZCMcu0TVOO6pz~AJoBcDy-Q1YuY_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp 54.192.125.128:443: i/o timeout

how happy? save me.....

**Comment by pkennedyr** [comment] 2016-05-18 04:47
Closing as fix has been released for this issue.

**Closed by pkennedyr** 2016-05-18 04:47 UTC

**Comment by starikovs** [comment] 2016-07-21 08:29
I have the same issue:
45d2c9dcb786: Image already exists 
4225c275f9fc: Image successfully pushed 
f8c046f4703b: Image successfully pushed 
341bb2600749: Image successfully pushed 
1df16a3830a0: Image successfully pushed 
7e94212dcb89: Image already exists 
3dce0d3d0c81: Image already exists 
41ef78fd36cd: Image push failed 
Error pushing to registry: Head https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/... :(
