### ISSUE TITLE
Issue with PHP DOI to ECR

### ISSUE THREAD

**Issue by matwilsondocker** [docker/hub-feedback#2341] opened 2023-08-24 13:53 UTC
## Problem description
The latest batch of PHP images (tags like 8.2.9-fpm-bullseye and 8.2.9-fpm-alpine) all seem to have manifests without any entries for linux/arm64/v8. This happened in the past as well.

Unfortunately, we have bit the tag limit allocated to us by AWS ECR.

**Comment by matwilsondocker** [comment] 2023-08-24 13:54
Raised with ECR and working with them to fix

**Comment by ldebrouwer** [comment] 2023-09-11 06:51
Hi there, is there an update on this by any chance? Ta!

**Comment by milosgajdos** [comment] 2023-09-11 08:13
Hi, unfortunately we're still awaiting response from AWS ECR team. Until they increase the Tag Limits we requested several weeks ago, we won't be able to do much about this.

**Comment by ldebrouwer** [comment] 2023-09-11 09:53
@milosgajdos Thank you for the update. I'm unsure as to how this was raised with the AWS ECR team, but in case you raised  a case with them, would you be able to share the case number with me, as I might be able to get some eyes on this through our AWS TAM, and expedite the resolution of this issue.

**Comment by ldebrouwer** [comment] 2023-09-11 12:42
Gotcha! Thank you very much, again 😊

**Comment by milosgajdos** [comment] 2023-09-12 09:48
@ldebrouwer we got the tag limit finally bumped and we've just triggered a sync; would you mind checking if everything is as expected in a few minutes and report back? Thanks!

**Comment by ldebrouwer** [comment] 2023-09-12 09:53
@milosgajdos I can confirm that I can now pull images/tags that I wasn't able to pull previously, so it looks like this has indeed been resolved. Thank you very much for getting this sorted.

**Comment by milosgajdos** [comment] 2023-09-12 09:55
I am now closing this issue. Thanks for the patience, unfortunately, this was truly out of our hands.

**Closed by milosgajdos** 2023-09-12 09:55 UTC
