### ISSUE TITLE
Could not find github repo

### ISSUE THREAD

**Issue by marcelosousaalmeida** [docker/hub-feedback#858] opened 2016-10-29 18:21 UTC
Hi,

I'm trying to add a new automated build to my Docker Hub but when i'm gonna to finalize the process it returns me the following error:

> Could not find github repo `marcelosousaalmeida/serf-rancher`

**Comment by reuteras** [comment] 2016-10-30 10:12
I can confirm the problem when I try to add a new automated build for my repo reuteras/container-rtir.

**Comment by edy** [comment] 2016-10-30 11:14
same here. could fix it by unlinking an linking back my github account.

**Comment by reuteras** [comment] 2016-10-30 11:30
Thank you for the tip @edy, solved the problem for me.

**Comment by a-dror** [comment] 2016-10-30 13:44
+1 urgent!
unlinking didn't help, progress currently blocked.

**Comment by G-Ray** [comment] 2016-10-30 14:53
+1, I'm unable to create my first automated build

**Comment by a-dror** [comment] 2016-10-30 14:54
it did work when I linked a user with 'owner' permissions

**Comment by bodsch** [comment] 2016-11-01 09:22
same here.

**Comment by jbelien** [comment] 2016-11-01 11:43
Hi, I had the same error.
My settings was giving access only to my public Github repositories.
I switched to access to my public **and private** repositories and the error disappeared.

**Comment by 31z4** [comment] 2016-11-02 04:27
+1 same thing!

**Comment by ruiznato** [comment] 2016-11-02 23:47
I can confirm, after un-linking and adding **public and private** access to my github account, I was able to create the automatic build.

**Comment by marcelosousaalmeida** [comment] 2016-11-03 09:25
Unlinking and linking accounts worked for me.

**Comment by wojas** [comment] 2016-11-03 14:29
This still does not work if you only allow public access. This issue needs to be reopened.

**Comment by marcusgrando** [comment] 2016-11-04 16:48
+1

**Comment by kak-tus** [comment] 2016-11-05 12:54
+1

**Comment by dimitrovs** [comment] 2016-11-06 04:05
+1

**Comment by pkennedyr** [comment] 2016-11-06 15:50
Thank you for the feedback - the team is looking into this issue.

**Comment by if-kenn** [comment] 2016-11-07 00:02
Argh, I cannot even do it if I unlink and re-link accounts.

**Comment by if-kenn** [comment] 2016-11-07 00:10
I was able to get it working because of the advice from @a-dror, made the user an "admin" on the github repo instead of just write permision and was able to create a automated build.

**Comment by mcrmonkey** [comment] 2016-11-09 21:31
I'm still having issues with this. Tried removing github link and recreating but no dice. 
This was working 2 weeks ago, whats changed ?

**Comment by ubswrk** [comment] 2016-11-10 15:41
+1
got this as well

**Comment by jolexa** [comment] 2016-11-10 15:44
My workaround was to follow @ruiznato 's advice then downgrade the account after the repo was added. After the initial setup, it seems like things work fine for subsequent docker builds.

**Comment by z** [comment] 2016-11-12 14:46
Just ran into this issue.

**Comment by keimoon** [comment] 2016-11-14 05:44
+1. This broke our build

**Comment by rmakulov** [comment] 2016-11-14 12:00
+1

**Comment by dmedov** [comment] 2016-11-14 13:00
+1

**Comment by dmedov** [comment] 2016-11-14 13:05
please take a look. we really need this

**Comment by omesser** [comment] 2016-11-14 13:19
+1

**Comment by pkennedyr** [comment] 2016-11-14 17:27
For those users encountering the "Could not find github repo namespace/rep" error, please confirm if the `Limited Access` option was selected when connecting your GitHub account to Docker Hub.

![docker-hub-github-permissions](https://cloud.githubusercontent.com/assets/16218086/20275215/8ac2405c-aa4c-11e6-99ba-004d3f34e4e3.png)

**Comment by dmedov** [comment] 2016-11-14 18:03
@pkennedyr yes, i selected "limited access"

**Comment by 31z4** [comment] 2016-11-14 18:03
It was.

**Comment by rmakulov** [comment] 2016-11-14 18:07
Confirm.

**Comment by omesser** [comment] 2016-11-14 22:44
Confirmed as well.
And, once I switched to the recommended option (Public+private) the repo was recognized and the problem was "solved".
But, It is important to me to reconnect the account with limited access only as the permissions granted with the first options are too wide for me personally

**Comment by keimoon** [comment] 2016-11-15 07:40
@pkennedyr I selected Public and Private (Recommended) but it still happened. Our repo name is `Dockerfiles`, and the error message said it could not find `..../dockerfiles`

**Comment by mcrmonkey** [comment] 2016-11-16 20:04
Its possible that this has now been fixed by docker.

Just added a new automated build about 5 mins ago and it went through as before.

Could everyone here re-test ?

+1 for fixed     -1 for not

**Comment by rmakulov** [comment] 2016-11-16 20:06
+1

**Comment by pkennedyr** [comment] 2016-11-16 20:56
[UPDATE] Earlier this morning, a fix was deployed to Docker Hub which addresses the "Could not find github repo namespace/repo" error when the `Limited Access` GitHub permission option is selected.

Thank you for the feedback and assistance in addressing the root cause of this issue.

**Closed by pkennedyr** 2016-11-16 20:56 UTC
