### ISSUE TITLE
Unable to create a new account

### ISSUE THREAD

**Issue by solalsolab** [docker/hub-feedback#1572] opened 2018-07-13 12:01 UTC
Hi there. 

Since I would like to discover blockchain applications, it's impossible for me to join the Docker Hub. "Username already taken" and "This email address is already associated with an account." are the sole message I get. You would told me to change username and email address, I've created a new email address, changed username, same problem...  
Any idea ?

Thanks a lot !

**Comment by kungfu71186** [comment] 2018-07-13 12:13
Same

#1304

**Comment by muhammedbasilsk** [comment] 2018-07-13 12:20
400 Bad request.
https://cloud.docker.com/v2/users/signup/

{"recaptcha_response": ["invalid recaptcha response"]}

**Comment by solalsolab** [comment] 2018-07-13 14:40
Hi everyone, thank you for answering. I'll try again in few hours.

**Comment by nandhini915** [comment] 2018-07-13 14:41
Hi, our signup/activation email issues should've resolved. If you haven't received an activation email yet, please respond to this ticket with your Docker user ID and we will manually activate (if you've signed up)

**Comment by AlexSurya** [comment] 2018-07-16 04:14
alexsurya this is my user id please activate it soon as possible thank you

**Comment by newbie-tan** [comment] 2018-07-16 05:54
HI, i have registered an  account ,but not receive the activation email,my email address is "newbiwtan@163.com". "newbiwtan" is the username ,please activate it soon ,or send another email. thank you

**Comment by schmutzlutz1** [comment] 2018-07-16 07:19
Hi,

Thanks for taking care of the Issue. I too am waiting for a 'stuck' activation.

My docker id is 'schmutzlutz1' and my email is 'schmutzlutz1@gmail.com'

Thanks a lot.

**Comment by thussss** [comment] 2018-07-17 06:03
Hi, please activate my account too, user ID: thuris, email: the_tha@163.com
Thanks

**Comment by nandhini915** [comment] 2018-07-17 17:13
Thanks for your feedback - I've opened an internal ticket and we will have our technical support engineers activating your accounts. 
Closing this ticket -- I'll post an update once these accounts are confirmed activated.

**Closed by nandhini915** 2018-07-17 17:13 UTC

**Comment by ambikayernal** [comment] 2019-07-24 05:36
Hi, I am unable to create docker hub account on sign up page. It's again and again asking for reCAPTCHA is required. Could anyone pls help with this issue. My dockerhub id and email as below.
id : ambikayernal
email : ambika.yernal@gmail.com

**Comment by slyubski** [comment] 2019-09-30 22:26
Hi,
I am also unable to create docker hub account ( to register docker ID) . 
Same reCAPTCHA problem. BTW .   
Looks like CHROME is not able  to connect to RECAPTCHA service though I am not sure. 
I saw the  youtube movie  how to solve this problem - simply upgrde chrome. 
Does not help on  WINDOWS. 
Note ! SAFARI on MAC does show (!!!!) the picture puzzle unlike chrome.  I p picked all  stairs and street lights :-) But it does not help. The net result is the same - error message 'reCaPTURE " is required.
I believe it is NOT RELIABLE security check if it depends on an external service.
Why all banking systems perfectly work ( not always but in  90% cases)  sending  the SECURITY CODE to the phone  (or email). 
The trivial problem to install docker on MAC and to play with it took me two hours and eventually I gave up.

**Comment by shekhu143** [comment] 2021-01-18 16:35
Hi guys, I have the solution for all of your concerns and issues, If you need to sort out... contact on this number 6303838776. If I tell you through message you cannot understand it. I hope it wont be misused....

**Comment by nabehfouda** [comment] 2021-01-28 23:53
Hi, please activate my account too, user ID: 1993, email:nabehfouda@gmail.com
Thanks

**Comment by jl111** [comment] 2022-05-07 05:39
i am unable to make a docker hub account
