### ISSUE TITLE
Multi-Stage builds on docker hub

### ISSUE THREAD

**Issue by captncraig** [docker/hub-feedback#1039] opened 2017-05-09 19:44 UTC
In trying to run multi-stage builds in a docker hub automated build: 

`Error parsing reference: "golang:1.7.3 as builder" is not a valid repository/tag: invalid reference format`

It looks like docker hub is not using the version of docker that supports this yet. Is there a timeline for when support will be availible?

**Comment by pkennedyr** [comment] 2017-05-09 20:28
Thanks for the feedback. The Docker Hub and Docker Cloud automated build service will be adding support for multi-stage builds when this feature graduates to the stable channel (currently targeted for June as part of the 17.06 release).

For more information on the Docker time-based release schedule, please see: https://docs.docker.com/engine/installation/#time-based-release-schedule

**Comment by captncraig** [comment] 2017-05-09 20:37
Thank you for the prompt feedback! Feel free to close this issue unless you'd rather leave it open until that release.

**Comment by medyagh** [comment] 2017-06-14 15:10
are we there there? 
(aka is it there multistage on dockerhub yet?)

**Comment by captncraig** [comment] 2017-06-14 15:13
I think not, my test app is still failing as of now: https://hub.docker.com/r/captncraig/multi-stage-test/builds/bu5tvny8jfhjzbsjg5rpw3s/

**Comment by pkennedyr** [comment] 2017-06-14 15:53
[UPDATE] Multi-stage builds are now available in Docker Cloud as part of the 5-30-2017 release:
https://forums.docker.com/t/docker-cloud-product-update-5-30-2017/32938

To take advantage of multi-stage builds (in Docker Cloud), select Edge (17.05.0-ce) as the Docker version of an automated repository. 

- Download the latest Edge release of [Docker for Mac](https://store.docker.com/editions/community/docker-ce-desktop-mac) or [Docker for Windows](https://store.docker.com/editions/community/docker-ce-desktop-windows) (to use multi-stage builds locally): 
- [How to use multi-stage builds](https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds)

We encourage you to try out Docker Cloud as this is where you will find support for this and many other autobuild features.

**Comment by medyagh** [comment] 2017-06-14 21:36
@pkennedyr is the multi stage build still scheduled for docker hub for this june ? or has that been cancelled and only available in docker cloud ?

**Comment by drasko** [comment] 2017-06-30 14:19
What's the conclusion - is Docker Hub getting multi-stage builds any time soon?

**Comment by pkennedyr** [comment] 2017-06-30 15:10
At the moment, there are no immediate plans to introduce multi-stage builds on Docker Hub. We encourage you to try out Docker Cloud as it is where you will find support for this and many other autobuild features.

**Comment by milsonian** [comment] 2017-06-30 16:11
I'm a bit confused...
> The biggest feature in 17.06 CE is that multi-stage builds, announced in April at DockerCon, have come to the stable release. 

So is Hub not going to go to 17.06 at any point?  Or are you pulling the feature from CE / will it be flagged / etc.?

**Comment by pkennedyr** [comment] 2017-06-30 19:02
@milsonian Apologies for the confusion, with availability of multi-stage builds in 17.06, this feature will also be available in Docker Hub when the corresponding upgrade to 17.06 occurs (ETA July). 

Note: Docker Cloud provides the ability to specify the Docker version (Stable or Edge) to use for an automated build, which enables access to the multi-stage build feature via the Edge channel today.

**Comment by milsonian** [comment] 2017-07-01 01:17
That's great, thanks for the clarification @pkennedyr!

**Comment by agc93** [comment] 2017-07-07 14:27
@pkennedyr Any update on when in July we can expect this feature on the Hub?

**Comment by pkennedyr** [comment] 2017-07-07 17:18
**Current ETA**: late July

We are currently awaiting availability of 17.06.01 CE GA, which includes a [bug fix](https://github.com/moby/moby/pull/33851) in multi-stage builds. Once available, we will update the Automated Build system with this new version and multi-stage builds will be available in Docker Hub.

**Comment by drasko** [comment] 2017-07-23 17:26
@pkennedyr any updates on the ETA?

**Comment by mghazizadeh** [comment] 2017-07-25 17:32
@drasko we are waiting GA release of 17.06.1 at the end of this month. We will update this thread in early August once the build service has been updated to that version.

**Comment by medyagh** [comment] 2017-07-26 17:33
sorry not related tot this issue @mghazizadeh  we have the same name ??? my name is Medya Ghazizadeh !

**Comment by llitfkitfk** [comment] 2017-08-01 04:04
currently you can use docker cloud for automated builds using multistage build (need config docker-ce edge version)

https://cloud.docker.com/app/username/repository/docker/username/imagename/builds/edit

**Comment by drasko** [comment] 2017-08-08 08:42
@mghazizadeh I do not get exactly - what do we wait with 17.06? From my understanding, it has been already released: https://blog.docker.com/2017/06/announcing-docker-17-06-community-edition-ce/

Do we wait for all these bugs to be fixed: https://github.com/moby/moby/milestone/69?

Also, what is not clear to me is why 17.06-ce is not present here: https://github.com/moby/moby/releases when it has been released...

**Comment by agc93** [comment] 2017-08-08 12:49
@drasko There's a prerelease rc2 available at the moment for a 17.06.01 release which I assume is what they are waiting for. 

Bit irritating that Hub users get left behind for a whole release because *reasons*, but I'd been looking for a reason to try out VSTS's Docker support and turns out it's excellent :laughing:

**Comment by thaJeztah** [comment] 2017-08-08 13:00
> what do we wait with 17.06? From my understanding, it has been already released

Docker Hub runs Docker EE (enterprise edition), not Docker CE (community edition). While Docker CE 17.06 has been released, Docker EE not yet

> Also, what is not clear to me is why 17.06-ce is not present here: https://github.com/moby/moby/releases when it has been released...

The moby/moby repository is now part of the Moby project, which is an upstream to Docker. What's in that repository is _one_ component in the Docker CE/Docker EE products. Releases are no longer done from that repository, but from the Docker CE repository; https://github.com/docker/docker-ce/releases

Note that (as mentioned earlier https://github.com/docker/hub-feedback/issues/1039#issuecomment-319261799), Docker Cloud allows you to [configure automated builds](https://docs.docker.com/docker-cloud/builds/automated-build/) and specify which version of Docker to run the builds on. Docker Cloud automated builds have additional features that may be interesting, and resulting images are also pushed to the same (Docker Hub) registry, so may be worth looking into if you want more advanced features.

**Comment by drasko** [comment] 2017-08-08 13:21
> Docker Hub runs Docker EE (enterprise edition), not Docker CE (community edition). While Docker CE 17.06 has been released, Docker EE not yet

Do we have any information today when it will be released, and more importantly when will DockerHub support it?

**Comment by thaJeztah** [comment] 2017-08-08 16:01
> Do we have any information today when it will be released, and more importantly when will DockerHub support it?

EE should be soon, but don't have a definitive date; for Docker Hub, I don't have that information, possibly @pkennedyr would know how long there's usually between release and "live" on Docker Hub

**Comment by ibnesayeed** [comment] 2017-08-10 20:36
> @thaJeztah: ... and resulting images are also pushed to the same (Docker Hub) registry ...

Thanks, I didn't know about it. What would happen if we set up automated builds for the same image in both the places (i.e., hub and cloud)?

**Comment by thaJeztah** [comment] 2017-08-12 18:26
If automated builds are configured on both, it's whichever was triggered last that pushes the image (well, they both push, but the last one will replace the previous one)

Looks like something we need to point out in the documentation (i.e. both Cloud and Hub using the same registry)

**Comment by ibnesayeed** [comment] 2017-08-12 18:46
Yes, this should be documented. I think there are many confusing bits, especially for those who are new to the ecosystem and did not witness it evolving. For example, currently there are three places to publish images, Hub, Store, and Cloud while they are all related and share pieces. Their separate distinguishing role might not be very clear to people.

**Comment by gesellix** [comment] 2017-08-16 20:04
FYI: https://blog.docker.com/2017/08/docker-enterprise-edition-17-06/
The countdown to multi-stage builds being available on Docker Hub has started ;-)

**Comment by ph-One** [comment] 2017-08-18 12:40
17.06.1-ce has dropped. Anxiously awaiting to see all my broken [multi-stage] builds start to run.

**Comment by mghazizadeh** [comment] 2017-08-18 14:27
@ph-One team is working on the upgrade for builders, please stay tuned.

**Comment by cglewis** [comment] 2017-08-21 14:43
works on Docker Hub now for me.

**Comment by ibnesayeed** [comment] 2017-08-21 15:56
> @cglewis: works on Docker Hub now for me.

I don't see any option to specify build-args though.

**Comment by pkennedyr** [comment] 2017-08-21 16:50
The Automated Build system has been updated with 17.06.01 CE, which enables multi-stage builds in Docker Hub.

**Comment by gesellix** [comment] 2017-08-21 21:08
It worked - but now it's reverted to Docker EE 17.03.1? See https://hub.docker.com/r/gesellix/wait-for/builds/btfvjxwqgzrhdhxxz55ilj6/ for an example.

**Comment by krambox** [comment] 2017-08-21 21:14
Same problem here - https://hub.docker.com/r/krambox/node-web-app/builds/bcqh2dvtrvqlin3aub4wptt/

**Comment by wilsontayar** [comment] 2017-08-21 21:16
@gesellix @krambox The same thing is happening to me on my automated builds as well. I'm getting it to work by triggering it manually for now (through the build settings menu). Guess not all nodes have been deployed yet.

**Comment by pchico83** [comment] 2017-08-21 21:29
We have rollbacked the 17.06.1 release since some builds were failing due to the upgrade.
We are working on fixing this issue and release 17.06.1 tomorrow again.

**Comment by gesellix** [comment] 2017-08-21 21:39
thanks for the quick feedback @pchico83

**Comment by pchico83** [comment] 2017-08-22 13:07
17.06.1 is running in prod again

**Comment by soulshake** [comment] 2017-08-31 17:16
@pchico83 Did this get rolled back again? My builds just abruptly changed from:
`Version: 17.06.1-ce` [[1](https://hub.docker.com/r/soulshake/worker-upstream/builds/btnqnvmxucoquznn9hguywj/)]
to:
`Version: 17.03.2-ee-5` [[2](https://hub.docker.com/r/soulshake/worker-upstream/builds/bihndvuujwgxgljy2bvvw5h/)]

**Comment by caervs** [comment] 2017-08-31 18:19
@soulshake we just had a brief regression that caused some builders to run older versions of Docker. Your builds should all be running on `17.06.1-ce` again. Thanks for commenting and please let us know if you have any issues.

**Closed by caervs** 2017-08-31 18:19 UTC

**Comment by TheYorkshireDev** [comment] 2017-08-31 21:54
@caervs I am having an issue since the upgrade, I am not sure if it is a regression since nobody is acknowledging my ticket #1145

**Comment by zhucebuliaolongchuan** [comment] 2018-08-29 16:42
Things works when I updated to version `18.06.1-ce`. 
Thanks~
