### ISSUE TITLE
Build failed: unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by jakirkham** [docker/hub-feedback#676] opened 2016-05-23 01:01 UTC
Running into this issue when trying to pull an image from another organization in an automated build. Here is there error message it gives me. Note I actually am in all relevant orgs and/or am the user whose image is being used when this happens. Also, all images being pulled are public images, but they may or may not be pulled by a public image build.

```
Build failed: Get https://registry-1.docker.io/v2/<USER>/<REPO>/manifests/latest: unauthorized: incorrect username or password
```

**Comment by mrproper** [comment] 2016-05-24 06:14
Getting the same thing here as of now

**Comment by rxwen** [comment] 2016-05-24 06:26
Same issue with my auto build docker image,  https://hub.docker.com/r/rxwen/golang-zeromq/builds/b38h9kvmym5zvdv9nc6raum/

**Comment by rynr** [comment] 2016-05-24 06:42
This is a duplicate of #630

**Comment by rxwen** [comment] 2016-05-24 06:50
I tried deleted my repository and created again, the issue is gone.
Though, it's not a good way to work around the issue.

**Comment by jakirkham** [comment] 2016-05-24 15:28
> I tried deleted my repository and created again, the issue is gone.

Sorry, should have added did the same and it seemed to work. The other repo I saw this on doesn't have this issue any more. So, I'm guessing this is resolved?

> Though, it's not a good way to work around the issue.

👍

**Comment by bcwalrus** [comment] 2016-06-03 22:07
We had an incident around 5/23 (https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5743f18e0e0ded6f1c000369), which explains the later failures.

@jakirkham I don't know what happened to your original issue. If you see this again, could you contact support@docker.com? Thanks!

**Closed by bcwalrus** 2016-06-03 22:07 UTC
