### ISSUE TITLE
Impossible to make pull mongo image from official repository

### ISSUE THREAD

**Issue by abuzzany** [docker/hub-feedback#1608] opened 2018-08-22 20:40 UTC
## Problem description
I can't download mongo image since 1 hour ago.
![screen shot 2018-08-22 at 15 37 29](https://user-images.githubusercontent.com/4792866/44489580-7614b400-a621-11e8-9f62-a328404f27ea.png)

**Comment by manishtomar** [comment] 2018-08-22 20:44
@abuzzany This is unfortunately a known issue when pushing multiarch library images where a multi-arch manifest without amd64/linux manifest is pushed. The issue is described in detail https://github.com/docker-library/official-images/issues/3835. It should be fixed automatically in sometime.

**Closed** 2018-08-23 18:14 UTC
