### ISSUE TITLE
Download count maxes out at int32

### ISSUE THREAD

**Issue by aeneasr** [docker/hub-feedback#1946] opened 2020-01-31 18:06 UTC
## Problem description

Images with over 2.1bn downloads no longer report download count correctly, most likely because an int32 (instead of int64) is used to track the count.

[Nginx](https://hub.docker.com/v2/repositories/library/nginx/) reports exactly `2147483647` which is the int32 upper limit. The count does not increase.

You probably never expected to hit 2.1bn+ downloads but here we are - congratulations :)

**Comment by manishtomar** [comment] 2020-07-29 16:50
Closing as duplicate of #2003

**Closed by manishtomar** 2020-07-29 16:50 UTC
Labels: bug
