### ISSUE TITLE
Automated Build going in pending state forever

### ISSUE THREAD

**Issue by viveklanjekar** [docker/hub-feedback#1370] opened 2018-02-15 08:47 UTC
I tried multiple times to do auto build, seems to go in pending state forever

https://hub.docker.com/r/viveklanjekar/vanila-zabbix/builds/brvaezhiaec72wdxqgunxd5/

**Comment by surajch123** [comment] 2018-02-15 10:18
I am also facing the same issue with docker-hub.  My build is queued from last 2 hours. Seems  something is wrong with docker-hub.

**Comment by mxschmitt** [comment] 2018-02-15 11:01
I have the same issue, pending for 1 hour now.

**Comment by janwerner** [comment] 2018-02-15 12:50
Same here

**Comment by dis1** [comment] 2018-02-15 13:05
Same problem. All builds are in "Queued" state for last 3 hours.

**Comment by jcaride** [comment] 2018-02-15 14:23
Same issue here. I tried to cancel the builds and start them again but nothing happens. They stay in "Queued" status

**Comment by stuartaccent** [comment] 2018-02-15 14:54
same

**Comment by joelbernstein** [comment] 2018-02-15 15:35
Amazing that Docker have been aware of this for an entire business day but still haven't fixed it.

Nobody's builds are running, anywhere. This is a HUGE FUCKING DEAL. We pay for private repos and autobuilds. Yet unless you're a customer of Docker "enterprise edition" this is all the support available.

Particularly insulting is that this >8 hour old issue has almost no useful information: https://status.docker.com/

**Comment by SattaRavi** [comment] 2018-02-15 17:02
same here

**Comment by mxschmitt** [comment] 2018-02-15 17:47
On my repository everything now works fine now :)

**Comment by porchn** [comment] 2018-02-16 00:41
same here

**Comment by pradeephbac** [comment] 2018-02-16 06:13
Still same here... docker build not pending for infinite time....!!!

**Comment by NeilClayton** [comment] 2018-02-16 09:48
Any news on resolving this issue???

**Comment by janwerner** [comment] 2018-02-16 15:10
Build failed with `Unexpected error`. We have a paid account, but not getting any reaction from their support. #fail

**Comment by paunin** [comment] 2018-02-22 10:08
Any help? 
https://hub.docker.com/r/postdock/pgpool/builds/ can;t build anything for a week

**Comment by chfast** [comment] 2018-02-22 12:26
https://hub.docker.com/r/ethereum/eth/builds/

**Comment by nandhini915** [comment] 2018-02-26 22:32
We had a lot of malicious usage happening over the last few weeks. Malicious users have been evicted as of now - we're monitoring builds and build health.

**Comment by capsulemon** [comment] 2018-03-29 11:01
The same issue.

Who has found a solution?

**Comment by bcroq** [comment] 2018-04-05 07:55
Same issue on https://hub.docker.com/r/bcroq/stackless/builds/ the builds are queued since 2 months!

**Comment by XelaRellum** [comment] 2018-04-07 22:49
My automated build show up as `Queued` for two days running now.

**Comment by millhaus** [comment] 2018-04-11 08:25
Same here since last afternoon. Can't even cancel the builds, it seems just frozen.
Is there any other way to cancel a queued build besides the hub GUI?

**Comment by ruipeng110** [comment] 2019-01-09 14:54
pending one hour ,manually.

**Closed** 2019-01-11 04:16 UTC

**Comment by daniel-dihardja** [comment] 2019-02-28 10:57
same issue here. pending since more than an hour

**Comment by hayaofr** [comment] 2019-02-28 11:03
same issue here. pending since more than an hour too.

**Comment by MarcinKosinski** [comment] 2019-02-28 15:26
same today

**Comment by DeanWronowski** [comment] 2019-03-01 16:30
Same here - been like it for almost a day now for me.

**Comment by nandhini915** [comment] 2019-03-01 16:34
Hello, thank you for highlighting this issue -- we'd updated status.docker.com informing our customers about an active incident on the Autobuild system. As of now we are able to remediate the situation. 

Could you folks provide your Docker IDs so we can crosscheck?

**Comment by dclong** [comment] 2019-03-11 05:20
Same here.

**Comment by jldevezas** [comment] 2019-05-07 14:06
And same here. Any news on this?

**Comment by vhorvath001** [comment] 2019-05-16 12:24
+

**Comment by khalilgharbaoui** [comment] 2019-05-18 01:14
+1

**Comment by koenhendriks** [comment] 2019-05-21 11:44
Same here

**Comment by azuken** [comment] 2019-05-21 12:49
Same

**Comment by lanarchyste** [comment] 2019-05-21 12:51
Same

**Comment by koenhendriks** [comment] 2019-05-21 13:19
If you have the same issue make sure to react with a 👍 on the original poster.

**Comment by KEINOS** [comment] 2019-05-29 01:42
Same issue. But in my case, it seems that **I used all the time quotas to build**. (Free plan for OpenSource)

It was because the other repos of mine, the `REPOSITORY LINKS` setting of `enable for base image` were enabled.

Since those repos use the same original base image, once the base image is updated, all the other related repos went to the queue and spent my time quota.

I canceled all the `PENDING` builds and left it overnight (more than 8hs) and then next day it started to work (build) properly again.

I couldn't find an official document about resource restrictions but in the forum.

> The current limits on Automated Builds are:
> 
>      2 hours
>      2 GB RAM
>      1 CPU
>      30 GB Disk Space
>
> (from the comment of "[Automated Build resource restrictions](https://forums.docker.com/t/automated-build-resource-restrictions/1413/2)" @ forums.docker.com )

It would be nice if I can check how much left I have though.

**Comment by murffious** [comment] 2019-06-11 01:39
same

**Comment by hirebarend** [comment] 2019-06-11 08:29
same

**Comment by tidoemanuele** [comment] 2019-06-11 13:42
same

**Comment by qhuy199** [comment] 2020-02-28 01:28
same

**Comment by zhuuvzhi** [comment] 2020-06-16 10:42
same

**Comment by symanovich-a** [comment] 2020-07-16 16:25
same

**Comment by RaimondB** [comment] 2020-07-17 05:11
yesterday and today I now have the same issue :-(

**Comment by djklim87** [comment] 2020-07-20 14:42
Same issue. Removing and adding entry does not helpful

**Comment by RaimondB** [comment] 2020-07-22 09:58
The next day things were working again, so seems to be some glitches in the docker hub infrastructure.
Maybe the build feature is to popular :-) 
I am thinking about only using the trigger and then use the github actions or travis to do the actual build.
That way I can stay uptodate with changing source images and not be dependent that much anymore on the docker hub infra.

**Comment by romanV7** [comment] 2020-10-09 15:47
> Same

me too

**Comment by natashagigcasters** [comment] 2021-05-26 16:39
This is currently happening to us yesterday evening and today.

**Comment by Dielee** [comment] 2021-05-27 18:17
Anyone knows why this is happening again ?

**Comment by natashagigcasters** [comment] 2021-05-27 18:33
I read on another thread that if you push a new update to Github (linked to a docker container), while it is building the previous update, that it will not be able to gracefully shut down and will therefore use up additional resources, causing a pending or slow-building state thereafter. I cannot confirm that this is the cause, but it seems likely the case for me as I was pushing multiple updates.

**Comment by Dielee** [comment] 2021-05-27 19:13
This seems to be the cause. Do you have a workaround for this case ? 
Stop all pending and trigger manual ?

**Comment by natashagigcasters** [comment] 2021-05-27 19:23
I tried that, to no avail. I even deleted the repository and re-created it but the resources were still clearly allocated as it was still slow. It would be nice if docker a setting or something to manually force kill and free-up one's own resources, in the case that this happens.

**Comment by Z-a-r-a-k-i** [comment] 2023-05-25 10:57
This is happening for us right now

**Comment by Z-a-r-a-k-i** [comment] 2023-05-25 14:16
Looks fixed 🥳
