### ISSUE TITLE
Cannot specify a Dockerfile that's not called Dockerfile

### ISSUE THREAD

**Issue by runseb** [docker/hub-feedback#412] opened 2015-10-21 09:19 UTC
Hi, when setting up an automated build we have to define the location of the Dockerfile.
It assumes that the location is a directory and the Dockerfile is called Dockerfile.

Apparently we cannot specify a Dockerfile named differently and specify an absolute path to it.

It would be quite nice, just like with docker build.

**Comment by jakirkham** [comment] 2015-10-22 15:38
Related to ( https://github.com/docker/hub-feedback/issues/292 ).

**Comment by ChristopherBiscardi** [comment] 2015-11-06 21:24
closing as dupe of https://github.com/docker/hub-feedback/issues/292

**Closed by ChristopherBiscardi** 2015-11-06 21:24 UTC
