### ISSUE TITLE
DockerHub Automated builds relative path in github

### ISSUE THREAD

**Issue by cesarjorgemartinez** [docker/hub-feedback#841] opened 2016-10-21 12:18 UTC
We have in github repository the docker file inside a folder:
./folder/Dockerfile
Then, when we configure an automated build, specifying the path: ./folder/Dockerfile, the automated build takes as root build ./folder/Dockerfile, and then, the in the docker file needs to use git clone to the repo, and use internally the branch, etc, and install the git client (More complexity, time and more image size in images, instead of use COPY)

Howto do for use dockerfiles that use the github root of a repository?

Like as docker or jenkins plugin do:
cd <git_repo_root_path>
"sudo docker build -f docker/Dockerfile ."

Regards,
Cesar Jorge

**Comment by Pierozi** [comment] 2016-11-09 15:49
Hello, I'm also tired to be forced to make a git clone and deal with workaround when need multiple refs.

Anything in backlog regarding option for root path as `-f` does ?

**Comment by pchico83** [comment] 2016-11-09 15:53
This feature has been released this week in Docker Cloud:
https://forums.docker.com/t/docker-cloud-release-notes-11-8-2016/24537
I would recommend to give Docker Cloud a try, this is the plan for Hub and Docker Cloud:
https://forums.docker.com/t/future-updates-on-docker-hub-docker-cloud/20498

**Comment by Pierozi** [comment] 2016-11-09 16:03
Ho well catch @pchico83 Build Context !

Many thanks i will jump a try on DockerCloud.

**Comment by HariSekhon** [comment] 2016-11-29 15:40
This is still an issue on DockerHub, completely unrelated changes touching a branch still trigger re-builds of all repos watching that branch instead of only the if the Dockerfile or it's parent directory's contents changed.

**Comment by Toflar** [comment] 2017-01-13 09:45
I guess this is a dupe of https://github.com/docker/hub-feedback/issues/292. I'm having the same issue, I need to be able to specify the context as well. In https://github.com/docker/hub-feedback/issues/292 @rrarunan stated that there's an update plan. That's quite long ago, any news on that? Thx :)

**Comment by Toflar** [comment] 2017-01-13 12:01
Oh, I missed this part:

> Is Hub going away? No, but the repository management and automated build features you love are being increasingly integrated into and expanded in Docker Cloud, and we recommend switching to Docker Cloud as your primary user interface.

Thanks for taking the time to reply! I'll check that out then :-)

**Comment by Pierozi** [comment] 2017-01-13 12:26
I confirm DockerCloud works as a breeze, maybe this issue can be closed ?

**Closed** 2017-01-13 15:17 UTC
